// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: avisio_ivi_data.proto
// Protobuf C++ Version: 6.31.0

#include "avisio_ivi_data.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace avisio_ivi {

inline constexpr SignalLightingStatus::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        timestamp_ms_{0u},
        turn_signals_{0u},
        exterior_lights_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR SignalLightingStatus::SignalLightingStatus(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SignalLightingStatus_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SignalLightingStatusDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SignalLightingStatusDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SignalLightingStatusDefaultTypeInternal() {}
  union {
    SignalLightingStatus _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SignalLightingStatusDefaultTypeInternal _SignalLightingStatus_default_instance_;

inline constexpr SafetyStatus::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        timestamp_ms_{0u},
        seatbelt_fastened_{false},
        airbag_ok_{false},
        abs_active_{false},
        traction_control_{false} {}

template <typename>
PROTOBUF_CONSTEXPR SafetyStatus::SafetyStatus(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SafetyStatus_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SafetyStatusDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SafetyStatusDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SafetyStatusDefaultTypeInternal() {}
  union {
    SafetyStatus _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SafetyStatusDefaultTypeInternal _SafetyStatus_default_instance_;

inline constexpr PrimaryVehicleState::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        timestamp_ms_{0u},
        speed_kmh_{0},
        current_drive_mode_{static_cast< ::avisio_ivi::DriveMode >(0)},
        battery_percent_{0u},
        motor_temp_c_{0},
        odometer_km_{0u},
        trip_distance_m_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR PrimaryVehicleState::PrimaryVehicleState(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PrimaryVehicleState_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PrimaryVehicleStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PrimaryVehicleStateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PrimaryVehicleStateDefaultTypeInternal() {}
  union {
    PrimaryVehicleState _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PrimaryVehicleStateDefaultTypeInternal _PrimaryVehicleState_default_instance_;
}  // namespace avisio_ivi
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_avisio_5fivi_5fdata_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_avisio_5fivi_5fdata_2eproto = nullptr;
const ::uint32_t
    TableStruct_avisio_5fivi_5fdata_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::avisio_ivi::PrimaryVehicleState, _impl_._has_bits_),
        10, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::avisio_ivi::PrimaryVehicleState, _impl_.timestamp_ms_),
        PROTOBUF_FIELD_OFFSET(::avisio_ivi::PrimaryVehicleState, _impl_.speed_kmh_),
        PROTOBUF_FIELD_OFFSET(::avisio_ivi::PrimaryVehicleState, _impl_.current_drive_mode_),
        PROTOBUF_FIELD_OFFSET(::avisio_ivi::PrimaryVehicleState, _impl_.battery_percent_),
        PROTOBUF_FIELD_OFFSET(::avisio_ivi::PrimaryVehicleState, _impl_.motor_temp_c_),
        PROTOBUF_FIELD_OFFSET(::avisio_ivi::PrimaryVehicleState, _impl_.odometer_km_),
        PROTOBUF_FIELD_OFFSET(::avisio_ivi::PrimaryVehicleState, _impl_.trip_distance_m_),
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::avisio_ivi::SignalLightingStatus, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::avisio_ivi::SignalLightingStatus, _impl_.timestamp_ms_),
        PROTOBUF_FIELD_OFFSET(::avisio_ivi::SignalLightingStatus, _impl_.turn_signals_),
        PROTOBUF_FIELD_OFFSET(::avisio_ivi::SignalLightingStatus, _impl_.exterior_lights_),
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::avisio_ivi::SafetyStatus, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::avisio_ivi::SafetyStatus, _impl_.timestamp_ms_),
        PROTOBUF_FIELD_OFFSET(::avisio_ivi::SafetyStatus, _impl_.seatbelt_fastened_),
        PROTOBUF_FIELD_OFFSET(::avisio_ivi::SafetyStatus, _impl_.airbag_ok_),
        PROTOBUF_FIELD_OFFSET(::avisio_ivi::SafetyStatus, _impl_.abs_active_),
        PROTOBUF_FIELD_OFFSET(::avisio_ivi::SafetyStatus, _impl_.traction_control_),
        0,
        1,
        2,
        3,
        4,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::avisio_ivi::PrimaryVehicleState)},
        {17, sizeof(::avisio_ivi::SignalLightingStatus)},
        {26, sizeof(::avisio_ivi::SafetyStatus)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::avisio_ivi::_PrimaryVehicleState_default_instance_._instance,
    &::avisio_ivi::_SignalLightingStatus_default_instance_._instance,
    &::avisio_ivi::_SafetyStatus_default_instance_._instance,
};
const char descriptor_table_protodef_avisio_5fivi_5fdata_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\025avisio_ivi_data.proto\022\navisio_ivi\"\316\001\n\023"
    "PrimaryVehicleState\022\024\n\014timestamp_ms\030\001 \001("
    "\r\022\021\n\tspeed_kmh\030\002 \001(\002\0221\n\022current_drive_mo"
    "de\030\003 \001(\0162\025.avisio_ivi.DriveMode\022\027\n\017batte"
    "ry_percent\030\004 \001(\r\022\024\n\014motor_temp_c\030\005 \001(\005\022\023"
    "\n\013odometer_km\030\006 \001(\r\022\027\n\017trip_distance_m\030\007"
    " \001(\r\"[\n\024SignalLightingStatus\022\024\n\014timestam"
    "p_ms\030\001 \001(\r\022\024\n\014turn_signals\030\002 \001(\r\022\027\n\017exte"
    "rior_lights\030\003 \001(\r\"\200\001\n\014SafetyStatus\022\024\n\014ti"
    "mestamp_ms\030\001 \001(\r\022\031\n\021seatbelt_fastened\030\002 "
    "\001(\010\022\021\n\tairbag_ok\030\003 \001(\010\022\022\n\nabs_active\030\004 \001"
    "(\010\022\030\n\020traction_control\030\005 \001(\010*|\n\tDriveMod"
    "e\022\023\n\017DRIVE_MODE_PARK\020\000\022\026\n\022DRIVE_MODE_REV"
    "ERSE\020\001\022\026\n\022DRIVE_MODE_NEUTRAL\020\002\022\024\n\020DRIVE_"
    "MODE_DRIVE\020\003\022\024\n\020DRIVE_MODE_BRAKE\020\004b\006prot"
    "o3"
};
static ::absl::once_flag descriptor_table_avisio_5fivi_5fdata_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_avisio_5fivi_5fdata_2eproto = {
    false,
    false,
    602,
    descriptor_table_protodef_avisio_5fivi_5fdata_2eproto,
    "avisio_ivi_data.proto",
    &descriptor_table_avisio_5fivi_5fdata_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_avisio_5fivi_5fdata_2eproto::offsets,
    file_level_enum_descriptors_avisio_5fivi_5fdata_2eproto,
    file_level_service_descriptors_avisio_5fivi_5fdata_2eproto,
};
namespace avisio_ivi {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL DriveMode_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_avisio_5fivi_5fdata_2eproto);
  return file_level_enum_descriptors_avisio_5fivi_5fdata_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t DriveMode_internal_data_[] = {
    327680u, 0u, };
// ===================================================================

class PrimaryVehicleState::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PrimaryVehicleState>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PrimaryVehicleState, _impl_._has_bits_);
};

PrimaryVehicleState::PrimaryVehicleState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PrimaryVehicleState_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:avisio_ivi.PrimaryVehicleState)
}
PrimaryVehicleState::PrimaryVehicleState(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PrimaryVehicleState& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PrimaryVehicleState_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE PrimaryVehicleState::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void PrimaryVehicleState::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, timestamp_ms_),
           0,
           offsetof(Impl_, trip_distance_m_) -
               offsetof(Impl_, timestamp_ms_) +
               sizeof(Impl_::trip_distance_m_));
}
PrimaryVehicleState::~PrimaryVehicleState() {
  // @@protoc_insertion_point(destructor:avisio_ivi.PrimaryVehicleState)
  SharedDtor(*this);
}
inline void PrimaryVehicleState::SharedDtor(MessageLite& self) {
  PrimaryVehicleState& this_ = static_cast<PrimaryVehicleState&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PrimaryVehicleState::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PrimaryVehicleState(arena);
}
constexpr auto PrimaryVehicleState::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(PrimaryVehicleState),
                                            alignof(PrimaryVehicleState));
}
constexpr auto PrimaryVehicleState::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PrimaryVehicleState_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PrimaryVehicleState::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PrimaryVehicleState>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PrimaryVehicleState::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PrimaryVehicleState>(), &PrimaryVehicleState::ByteSizeLong,
              &PrimaryVehicleState::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PrimaryVehicleState, _impl_._cached_size_),
          false,
      },
      &PrimaryVehicleState::kDescriptorMethods,
      &descriptor_table_avisio_5fivi_5fdata_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PrimaryVehicleState_class_data_ =
        PrimaryVehicleState::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PrimaryVehicleState::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PrimaryVehicleState_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PrimaryVehicleState_class_data_.tc_table);
  return PrimaryVehicleState_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 0, 0, 2>
PrimaryVehicleState::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PrimaryVehicleState, _impl_._has_bits_),
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PrimaryVehicleState_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::avisio_ivi::PrimaryVehicleState>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 timestamp_ms = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PrimaryVehicleState, _impl_.timestamp_ms_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(PrimaryVehicleState, _impl_.timestamp_ms_)}},
    // float speed_kmh = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 1, 0, PROTOBUF_FIELD_OFFSET(PrimaryVehicleState, _impl_.speed_kmh_)}},
    // .avisio_ivi.DriveMode current_drive_mode = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PrimaryVehicleState, _impl_.current_drive_mode_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(PrimaryVehicleState, _impl_.current_drive_mode_)}},
    // uint32 battery_percent = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PrimaryVehicleState, _impl_.battery_percent_), 3>(),
     {32, 3, 0, PROTOBUF_FIELD_OFFSET(PrimaryVehicleState, _impl_.battery_percent_)}},
    // int32 motor_temp_c = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PrimaryVehicleState, _impl_.motor_temp_c_), 4>(),
     {40, 4, 0, PROTOBUF_FIELD_OFFSET(PrimaryVehicleState, _impl_.motor_temp_c_)}},
    // uint32 odometer_km = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PrimaryVehicleState, _impl_.odometer_km_), 5>(),
     {48, 5, 0, PROTOBUF_FIELD_OFFSET(PrimaryVehicleState, _impl_.odometer_km_)}},
    // uint32 trip_distance_m = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PrimaryVehicleState, _impl_.trip_distance_m_), 6>(),
     {56, 6, 0, PROTOBUF_FIELD_OFFSET(PrimaryVehicleState, _impl_.trip_distance_m_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 timestamp_ms = 1;
    {PROTOBUF_FIELD_OFFSET(PrimaryVehicleState, _impl_.timestamp_ms_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // float speed_kmh = 2;
    {PROTOBUF_FIELD_OFFSET(PrimaryVehicleState, _impl_.speed_kmh_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // .avisio_ivi.DriveMode current_drive_mode = 3;
    {PROTOBUF_FIELD_OFFSET(PrimaryVehicleState, _impl_.current_drive_mode_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // uint32 battery_percent = 4;
    {PROTOBUF_FIELD_OFFSET(PrimaryVehicleState, _impl_.battery_percent_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // int32 motor_temp_c = 5;
    {PROTOBUF_FIELD_OFFSET(PrimaryVehicleState, _impl_.motor_temp_c_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // uint32 odometer_km = 6;
    {PROTOBUF_FIELD_OFFSET(PrimaryVehicleState, _impl_.odometer_km_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 trip_distance_m = 7;
    {PROTOBUF_FIELD_OFFSET(PrimaryVehicleState, _impl_.trip_distance_m_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void PrimaryVehicleState::Clear() {
// @@protoc_insertion_point(message_clear_start:avisio_ivi.PrimaryVehicleState)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000007fu) != 0) {
    ::memset(&_impl_.timestamp_ms_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.trip_distance_m_) -
        reinterpret_cast<char*>(&_impl_.timestamp_ms_)) + sizeof(_impl_.trip_distance_m_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PrimaryVehicleState::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PrimaryVehicleState& this_ = static_cast<const PrimaryVehicleState&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PrimaryVehicleState::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PrimaryVehicleState& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:avisio_ivi.PrimaryVehicleState)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 timestamp_ms = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_timestamp_ms() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_timestamp_ms(), target);
    }
  }

  // float speed_kmh = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_speed_kmh()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          2, this_._internal_speed_kmh(), target);
    }
  }

  // .avisio_ivi.DriveMode current_drive_mode = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (this_._internal_current_drive_mode() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          3, this_._internal_current_drive_mode(), target);
    }
  }

  // uint32 battery_percent = 4;
  if ((this_._impl_._has_bits_[0] & 0x00000008u) != 0) {
    if (this_._internal_battery_percent() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          4, this_._internal_battery_percent(), target);
    }
  }

  // int32 motor_temp_c = 5;
  if ((this_._impl_._has_bits_[0] & 0x00000010u) != 0) {
    if (this_._internal_motor_temp_c() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<5>(
              stream, this_._internal_motor_temp_c(), target);
    }
  }

  // uint32 odometer_km = 6;
  if ((this_._impl_._has_bits_[0] & 0x00000020u) != 0) {
    if (this_._internal_odometer_km() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          6, this_._internal_odometer_km(), target);
    }
  }

  // uint32 trip_distance_m = 7;
  if ((this_._impl_._has_bits_[0] & 0x00000040u) != 0) {
    if (this_._internal_trip_distance_m() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          7, this_._internal_trip_distance_m(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:avisio_ivi.PrimaryVehicleState)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PrimaryVehicleState::ByteSizeLong(const MessageLite& base) {
  const PrimaryVehicleState& this_ = static_cast<const PrimaryVehicleState&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PrimaryVehicleState::ByteSizeLong() const {
  const PrimaryVehicleState& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:avisio_ivi.PrimaryVehicleState)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000007fu) != 0) {
    // uint32 timestamp_ms = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_timestamp_ms() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_timestamp_ms());
      }
    }
    // float speed_kmh = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_speed_kmh()) != 0) {
        total_size += 5;
      }
    }
    // .avisio_ivi.DriveMode current_drive_mode = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (this_._internal_current_drive_mode() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_current_drive_mode());
      }
    }
    // uint32 battery_percent = 4;
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (this_._internal_battery_percent() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_battery_percent());
      }
    }
    // int32 motor_temp_c = 5;
    if ((cached_has_bits & 0x00000010u) != 0) {
      if (this_._internal_motor_temp_c() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_motor_temp_c());
      }
    }
    // uint32 odometer_km = 6;
    if ((cached_has_bits & 0x00000020u) != 0) {
      if (this_._internal_odometer_km() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_odometer_km());
      }
    }
    // uint32 trip_distance_m = 7;
    if ((cached_has_bits & 0x00000040u) != 0) {
      if (this_._internal_trip_distance_m() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_trip_distance_m());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PrimaryVehicleState::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PrimaryVehicleState*>(&to_msg);
  auto& from = static_cast<const PrimaryVehicleState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:avisio_ivi.PrimaryVehicleState)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000007fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (from._internal_timestamp_ms() != 0) {
        _this->_impl_.timestamp_ms_ = from._impl_.timestamp_ms_;
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (::absl::bit_cast<::uint32_t>(from._internal_speed_kmh()) != 0) {
        _this->_impl_.speed_kmh_ = from._impl_.speed_kmh_;
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (from._internal_current_drive_mode() != 0) {
        _this->_impl_.current_drive_mode_ = from._impl_.current_drive_mode_;
      }
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (from._internal_battery_percent() != 0) {
        _this->_impl_.battery_percent_ = from._impl_.battery_percent_;
      }
    }
    if ((cached_has_bits & 0x00000010u) != 0) {
      if (from._internal_motor_temp_c() != 0) {
        _this->_impl_.motor_temp_c_ = from._impl_.motor_temp_c_;
      }
    }
    if ((cached_has_bits & 0x00000020u) != 0) {
      if (from._internal_odometer_km() != 0) {
        _this->_impl_.odometer_km_ = from._impl_.odometer_km_;
      }
    }
    if ((cached_has_bits & 0x00000040u) != 0) {
      if (from._internal_trip_distance_m() != 0) {
        _this->_impl_.trip_distance_m_ = from._impl_.trip_distance_m_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PrimaryVehicleState::CopyFrom(const PrimaryVehicleState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:avisio_ivi.PrimaryVehicleState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PrimaryVehicleState::InternalSwap(PrimaryVehicleState* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PrimaryVehicleState, _impl_.trip_distance_m_)
      + sizeof(PrimaryVehicleState::_impl_.trip_distance_m_)
      - PROTOBUF_FIELD_OFFSET(PrimaryVehicleState, _impl_.timestamp_ms_)>(
          reinterpret_cast<char*>(&_impl_.timestamp_ms_),
          reinterpret_cast<char*>(&other->_impl_.timestamp_ms_));
}

::google::protobuf::Metadata PrimaryVehicleState::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SignalLightingStatus::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SignalLightingStatus>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SignalLightingStatus, _impl_._has_bits_);
};

SignalLightingStatus::SignalLightingStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SignalLightingStatus_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:avisio_ivi.SignalLightingStatus)
}
SignalLightingStatus::SignalLightingStatus(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SignalLightingStatus& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SignalLightingStatus_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE SignalLightingStatus::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void SignalLightingStatus::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, timestamp_ms_),
           0,
           offsetof(Impl_, exterior_lights_) -
               offsetof(Impl_, timestamp_ms_) +
               sizeof(Impl_::exterior_lights_));
}
SignalLightingStatus::~SignalLightingStatus() {
  // @@protoc_insertion_point(destructor:avisio_ivi.SignalLightingStatus)
  SharedDtor(*this);
}
inline void SignalLightingStatus::SharedDtor(MessageLite& self) {
  SignalLightingStatus& this_ = static_cast<SignalLightingStatus&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SignalLightingStatus::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SignalLightingStatus(arena);
}
constexpr auto SignalLightingStatus::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SignalLightingStatus),
                                            alignof(SignalLightingStatus));
}
constexpr auto SignalLightingStatus::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SignalLightingStatus_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SignalLightingStatus::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SignalLightingStatus>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SignalLightingStatus::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SignalLightingStatus>(), &SignalLightingStatus::ByteSizeLong,
              &SignalLightingStatus::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SignalLightingStatus, _impl_._cached_size_),
          false,
      },
      &SignalLightingStatus::kDescriptorMethods,
      &descriptor_table_avisio_5fivi_5fdata_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SignalLightingStatus_class_data_ =
        SignalLightingStatus::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SignalLightingStatus::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SignalLightingStatus_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SignalLightingStatus_class_data_.tc_table);
  return SignalLightingStatus_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
SignalLightingStatus::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SignalLightingStatus, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SignalLightingStatus_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::avisio_ivi::SignalLightingStatus>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 timestamp_ms = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SignalLightingStatus, _impl_.timestamp_ms_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(SignalLightingStatus, _impl_.timestamp_ms_)}},
    // uint32 turn_signals = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SignalLightingStatus, _impl_.turn_signals_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(SignalLightingStatus, _impl_.turn_signals_)}},
    // uint32 exterior_lights = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SignalLightingStatus, _impl_.exterior_lights_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(SignalLightingStatus, _impl_.exterior_lights_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 timestamp_ms = 1;
    {PROTOBUF_FIELD_OFFSET(SignalLightingStatus, _impl_.timestamp_ms_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 turn_signals = 2;
    {PROTOBUF_FIELD_OFFSET(SignalLightingStatus, _impl_.turn_signals_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 exterior_lights = 3;
    {PROTOBUF_FIELD_OFFSET(SignalLightingStatus, _impl_.exterior_lights_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void SignalLightingStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:avisio_ivi.SignalLightingStatus)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    ::memset(&_impl_.timestamp_ms_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.exterior_lights_) -
        reinterpret_cast<char*>(&_impl_.timestamp_ms_)) + sizeof(_impl_.exterior_lights_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SignalLightingStatus::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SignalLightingStatus& this_ = static_cast<const SignalLightingStatus&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SignalLightingStatus::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SignalLightingStatus& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:avisio_ivi.SignalLightingStatus)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 timestamp_ms = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_timestamp_ms() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_timestamp_ms(), target);
    }
  }

  // uint32 turn_signals = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (this_._internal_turn_signals() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          2, this_._internal_turn_signals(), target);
    }
  }

  // uint32 exterior_lights = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (this_._internal_exterior_lights() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          3, this_._internal_exterior_lights(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:avisio_ivi.SignalLightingStatus)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SignalLightingStatus::ByteSizeLong(const MessageLite& base) {
  const SignalLightingStatus& this_ = static_cast<const SignalLightingStatus&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SignalLightingStatus::ByteSizeLong() const {
  const SignalLightingStatus& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:avisio_ivi.SignalLightingStatus)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    // uint32 timestamp_ms = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_timestamp_ms() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_timestamp_ms());
      }
    }
    // uint32 turn_signals = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (this_._internal_turn_signals() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_turn_signals());
      }
    }
    // uint32 exterior_lights = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (this_._internal_exterior_lights() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_exterior_lights());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SignalLightingStatus::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SignalLightingStatus*>(&to_msg);
  auto& from = static_cast<const SignalLightingStatus&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:avisio_ivi.SignalLightingStatus)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (from._internal_timestamp_ms() != 0) {
        _this->_impl_.timestamp_ms_ = from._impl_.timestamp_ms_;
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (from._internal_turn_signals() != 0) {
        _this->_impl_.turn_signals_ = from._impl_.turn_signals_;
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (from._internal_exterior_lights() != 0) {
        _this->_impl_.exterior_lights_ = from._impl_.exterior_lights_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SignalLightingStatus::CopyFrom(const SignalLightingStatus& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:avisio_ivi.SignalLightingStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SignalLightingStatus::InternalSwap(SignalLightingStatus* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SignalLightingStatus, _impl_.exterior_lights_)
      + sizeof(SignalLightingStatus::_impl_.exterior_lights_)
      - PROTOBUF_FIELD_OFFSET(SignalLightingStatus, _impl_.timestamp_ms_)>(
          reinterpret_cast<char*>(&_impl_.timestamp_ms_),
          reinterpret_cast<char*>(&other->_impl_.timestamp_ms_));
}

::google::protobuf::Metadata SignalLightingStatus::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SafetyStatus::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SafetyStatus>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SafetyStatus, _impl_._has_bits_);
};

SafetyStatus::SafetyStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SafetyStatus_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:avisio_ivi.SafetyStatus)
}
SafetyStatus::SafetyStatus(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SafetyStatus& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SafetyStatus_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE SafetyStatus::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void SafetyStatus::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, timestamp_ms_),
           0,
           offsetof(Impl_, traction_control_) -
               offsetof(Impl_, timestamp_ms_) +
               sizeof(Impl_::traction_control_));
}
SafetyStatus::~SafetyStatus() {
  // @@protoc_insertion_point(destructor:avisio_ivi.SafetyStatus)
  SharedDtor(*this);
}
inline void SafetyStatus::SharedDtor(MessageLite& self) {
  SafetyStatus& this_ = static_cast<SafetyStatus&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SafetyStatus::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SafetyStatus(arena);
}
constexpr auto SafetyStatus::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SafetyStatus),
                                            alignof(SafetyStatus));
}
constexpr auto SafetyStatus::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SafetyStatus_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SafetyStatus::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SafetyStatus>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SafetyStatus::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SafetyStatus>(), &SafetyStatus::ByteSizeLong,
              &SafetyStatus::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SafetyStatus, _impl_._cached_size_),
          false,
      },
      &SafetyStatus::kDescriptorMethods,
      &descriptor_table_avisio_5fivi_5fdata_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SafetyStatus_class_data_ =
        SafetyStatus::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SafetyStatus::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SafetyStatus_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SafetyStatus_class_data_.tc_table);
  return SafetyStatus_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 0, 2>
SafetyStatus::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SafetyStatus, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SafetyStatus_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::avisio_ivi::SafetyStatus>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 timestamp_ms = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SafetyStatus, _impl_.timestamp_ms_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(SafetyStatus, _impl_.timestamp_ms_)}},
    // bool seatbelt_fastened = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SafetyStatus, _impl_.seatbelt_fastened_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(SafetyStatus, _impl_.seatbelt_fastened_)}},
    // bool airbag_ok = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SafetyStatus, _impl_.airbag_ok_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(SafetyStatus, _impl_.airbag_ok_)}},
    // bool abs_active = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SafetyStatus, _impl_.abs_active_), 3>(),
     {32, 3, 0, PROTOBUF_FIELD_OFFSET(SafetyStatus, _impl_.abs_active_)}},
    // bool traction_control = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SafetyStatus, _impl_.traction_control_), 4>(),
     {40, 4, 0, PROTOBUF_FIELD_OFFSET(SafetyStatus, _impl_.traction_control_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 timestamp_ms = 1;
    {PROTOBUF_FIELD_OFFSET(SafetyStatus, _impl_.timestamp_ms_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // bool seatbelt_fastened = 2;
    {PROTOBUF_FIELD_OFFSET(SafetyStatus, _impl_.seatbelt_fastened_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // bool airbag_ok = 3;
    {PROTOBUF_FIELD_OFFSET(SafetyStatus, _impl_.airbag_ok_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // bool abs_active = 4;
    {PROTOBUF_FIELD_OFFSET(SafetyStatus, _impl_.abs_active_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // bool traction_control = 5;
    {PROTOBUF_FIELD_OFFSET(SafetyStatus, _impl_.traction_control_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void SafetyStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:avisio_ivi.SafetyStatus)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    ::memset(&_impl_.timestamp_ms_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.traction_control_) -
        reinterpret_cast<char*>(&_impl_.timestamp_ms_)) + sizeof(_impl_.traction_control_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SafetyStatus::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SafetyStatus& this_ = static_cast<const SafetyStatus&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SafetyStatus::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SafetyStatus& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:avisio_ivi.SafetyStatus)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 timestamp_ms = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_timestamp_ms() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_timestamp_ms(), target);
    }
  }

  // bool seatbelt_fastened = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (this_._internal_seatbelt_fastened() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          2, this_._internal_seatbelt_fastened(), target);
    }
  }

  // bool airbag_ok = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (this_._internal_airbag_ok() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          3, this_._internal_airbag_ok(), target);
    }
  }

  // bool abs_active = 4;
  if ((this_._impl_._has_bits_[0] & 0x00000008u) != 0) {
    if (this_._internal_abs_active() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          4, this_._internal_abs_active(), target);
    }
  }

  // bool traction_control = 5;
  if ((this_._impl_._has_bits_[0] & 0x00000010u) != 0) {
    if (this_._internal_traction_control() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          5, this_._internal_traction_control(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:avisio_ivi.SafetyStatus)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SafetyStatus::ByteSizeLong(const MessageLite& base) {
  const SafetyStatus& this_ = static_cast<const SafetyStatus&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SafetyStatus::ByteSizeLong() const {
  const SafetyStatus& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:avisio_ivi.SafetyStatus)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    // uint32 timestamp_ms = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_timestamp_ms() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_timestamp_ms());
      }
    }
    // bool seatbelt_fastened = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (this_._internal_seatbelt_fastened() != 0) {
        total_size += 2;
      }
    }
    // bool airbag_ok = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (this_._internal_airbag_ok() != 0) {
        total_size += 2;
      }
    }
    // bool abs_active = 4;
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (this_._internal_abs_active() != 0) {
        total_size += 2;
      }
    }
    // bool traction_control = 5;
    if ((cached_has_bits & 0x00000010u) != 0) {
      if (this_._internal_traction_control() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SafetyStatus::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SafetyStatus*>(&to_msg);
  auto& from = static_cast<const SafetyStatus&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:avisio_ivi.SafetyStatus)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (from._internal_timestamp_ms() != 0) {
        _this->_impl_.timestamp_ms_ = from._impl_.timestamp_ms_;
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (from._internal_seatbelt_fastened() != 0) {
        _this->_impl_.seatbelt_fastened_ = from._impl_.seatbelt_fastened_;
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (from._internal_airbag_ok() != 0) {
        _this->_impl_.airbag_ok_ = from._impl_.airbag_ok_;
      }
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (from._internal_abs_active() != 0) {
        _this->_impl_.abs_active_ = from._impl_.abs_active_;
      }
    }
    if ((cached_has_bits & 0x00000010u) != 0) {
      if (from._internal_traction_control() != 0) {
        _this->_impl_.traction_control_ = from._impl_.traction_control_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SafetyStatus::CopyFrom(const SafetyStatus& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:avisio_ivi.SafetyStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SafetyStatus::InternalSwap(SafetyStatus* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SafetyStatus, _impl_.traction_control_)
      + sizeof(SafetyStatus::_impl_.traction_control_)
      - PROTOBUF_FIELD_OFFSET(SafetyStatus, _impl_.timestamp_ms_)>(
          reinterpret_cast<char*>(&_impl_.timestamp_ms_),
          reinterpret_cast<char*>(&other->_impl_.timestamp_ms_));
}

::google::protobuf::Metadata SafetyStatus::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace avisio_ivi
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_avisio_5fivi_5fdata_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
