// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: avisio_ivi_data.proto
// Protobuf C++ Version: 6.31.0

#ifndef avisio_5fivi_5fdata_2eproto_2epb_2eh
#define avisio_5fivi_5fdata_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_avisio_5fivi_5fdata_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_avisio_5fivi_5fdata_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_avisio_5fivi_5fdata_2eproto;
}  // extern "C"
namespace avisio_ivi {
enum DriveMode : int;
extern const uint32_t DriveMode_internal_data_[];
class PrimaryVehicleState;
struct PrimaryVehicleStateDefaultTypeInternal;
extern PrimaryVehicleStateDefaultTypeInternal _PrimaryVehicleState_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PrimaryVehicleState_class_data_;
class SafetyStatus;
struct SafetyStatusDefaultTypeInternal;
extern SafetyStatusDefaultTypeInternal _SafetyStatus_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SafetyStatus_class_data_;
class SignalLightingStatus;
struct SignalLightingStatusDefaultTypeInternal;
extern SignalLightingStatusDefaultTypeInternal _SignalLightingStatus_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SignalLightingStatus_class_data_;
}  // namespace avisio_ivi
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::avisio_ivi::DriveMode_internal_data_>
    internal::EnumTraitsImpl::value<::avisio_ivi::DriveMode>;
}  // namespace protobuf
}  // namespace google

namespace avisio_ivi {
enum DriveMode : int {
  DRIVE_MODE_PARK = 0,
  DRIVE_MODE_REVERSE = 1,
  DRIVE_MODE_NEUTRAL = 2,
  DRIVE_MODE_DRIVE = 3,
  DRIVE_MODE_BRAKE = 4,
  DriveMode_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  DriveMode_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t DriveMode_internal_data_[];
inline constexpr DriveMode DriveMode_MIN =
    static_cast<DriveMode>(0);
inline constexpr DriveMode DriveMode_MAX =
    static_cast<DriveMode>(4);
inline bool DriveMode_IsValid(int value) {
  return 0 <= value && value <= 4;
}
inline constexpr int DriveMode_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL DriveMode_descriptor();
template <typename T>
const ::std::string& DriveMode_Name(T value) {
  static_assert(::std::is_same<T, DriveMode>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to DriveMode_Name().");
  return DriveMode_Name(static_cast<DriveMode>(value));
}
template <>
inline const ::std::string& DriveMode_Name(DriveMode value) {
  return ::google::protobuf::internal::NameOfDenseEnum<DriveMode_descriptor, 0, 4>(
      static_cast<int>(value));
}
inline bool DriveMode_Parse(
    ::absl::string_view name, DriveMode* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<DriveMode>(DriveMode_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class SignalLightingStatus final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:avisio_ivi.SignalLightingStatus) */ {
 public:
  inline SignalLightingStatus() : SignalLightingStatus(nullptr) {}
  ~SignalLightingStatus() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SignalLightingStatus* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SignalLightingStatus));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SignalLightingStatus(::google::protobuf::internal::ConstantInitialized);

  inline SignalLightingStatus(const SignalLightingStatus& from) : SignalLightingStatus(nullptr, from) {}
  inline SignalLightingStatus(SignalLightingStatus&& from) noexcept
      : SignalLightingStatus(nullptr, ::std::move(from)) {}
  inline SignalLightingStatus& operator=(const SignalLightingStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline SignalLightingStatus& operator=(SignalLightingStatus&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SignalLightingStatus& default_instance() {
    return *reinterpret_cast<const SignalLightingStatus*>(
        &_SignalLightingStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(SignalLightingStatus& a, SignalLightingStatus& b) { a.Swap(&b); }
  inline void Swap(SignalLightingStatus* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SignalLightingStatus* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SignalLightingStatus* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SignalLightingStatus>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SignalLightingStatus& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SignalLightingStatus& from) { SignalLightingStatus::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SignalLightingStatus* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "avisio_ivi.SignalLightingStatus"; }

 protected:
  explicit SignalLightingStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SignalLightingStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SignalLightingStatus& from);
  SignalLightingStatus(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SignalLightingStatus&& from) noexcept
      : SignalLightingStatus(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTimestampMsFieldNumber = 1,
    kTurnSignalsFieldNumber = 2,
    kExteriorLightsFieldNumber = 3,
  };
  // uint32 timestamp_ms = 1;
  void clear_timestamp_ms() ;
  ::uint32_t timestamp_ms() const;
  void set_timestamp_ms(::uint32_t value);

  private:
  ::uint32_t _internal_timestamp_ms() const;
  void _internal_set_timestamp_ms(::uint32_t value);

  public:
  // uint32 turn_signals = 2;
  void clear_turn_signals() ;
  ::uint32_t turn_signals() const;
  void set_turn_signals(::uint32_t value);

  private:
  ::uint32_t _internal_turn_signals() const;
  void _internal_set_turn_signals(::uint32_t value);

  public:
  // uint32 exterior_lights = 3;
  void clear_exterior_lights() ;
  ::uint32_t exterior_lights() const;
  void set_exterior_lights(::uint32_t value);

  private:
  ::uint32_t _internal_exterior_lights() const;
  void _internal_set_exterior_lights(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:avisio_ivi.SignalLightingStatus)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SignalLightingStatus& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t timestamp_ms_;
    ::uint32_t turn_signals_;
    ::uint32_t exterior_lights_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_avisio_5fivi_5fdata_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SignalLightingStatus_class_data_;
// -------------------------------------------------------------------

class SafetyStatus final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:avisio_ivi.SafetyStatus) */ {
 public:
  inline SafetyStatus() : SafetyStatus(nullptr) {}
  ~SafetyStatus() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SafetyStatus* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SafetyStatus));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SafetyStatus(::google::protobuf::internal::ConstantInitialized);

  inline SafetyStatus(const SafetyStatus& from) : SafetyStatus(nullptr, from) {}
  inline SafetyStatus(SafetyStatus&& from) noexcept
      : SafetyStatus(nullptr, ::std::move(from)) {}
  inline SafetyStatus& operator=(const SafetyStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline SafetyStatus& operator=(SafetyStatus&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SafetyStatus& default_instance() {
    return *reinterpret_cast<const SafetyStatus*>(
        &_SafetyStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(SafetyStatus& a, SafetyStatus& b) { a.Swap(&b); }
  inline void Swap(SafetyStatus* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SafetyStatus* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SafetyStatus* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SafetyStatus>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SafetyStatus& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SafetyStatus& from) { SafetyStatus::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SafetyStatus* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "avisio_ivi.SafetyStatus"; }

 protected:
  explicit SafetyStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SafetyStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SafetyStatus& from);
  SafetyStatus(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SafetyStatus&& from) noexcept
      : SafetyStatus(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTimestampMsFieldNumber = 1,
    kSeatbeltFastenedFieldNumber = 2,
    kAirbagOkFieldNumber = 3,
    kAbsActiveFieldNumber = 4,
    kTractionControlFieldNumber = 5,
  };
  // uint32 timestamp_ms = 1;
  void clear_timestamp_ms() ;
  ::uint32_t timestamp_ms() const;
  void set_timestamp_ms(::uint32_t value);

  private:
  ::uint32_t _internal_timestamp_ms() const;
  void _internal_set_timestamp_ms(::uint32_t value);

  public:
  // bool seatbelt_fastened = 2;
  void clear_seatbelt_fastened() ;
  bool seatbelt_fastened() const;
  void set_seatbelt_fastened(bool value);

  private:
  bool _internal_seatbelt_fastened() const;
  void _internal_set_seatbelt_fastened(bool value);

  public:
  // bool airbag_ok = 3;
  void clear_airbag_ok() ;
  bool airbag_ok() const;
  void set_airbag_ok(bool value);

  private:
  bool _internal_airbag_ok() const;
  void _internal_set_airbag_ok(bool value);

  public:
  // bool abs_active = 4;
  void clear_abs_active() ;
  bool abs_active() const;
  void set_abs_active(bool value);

  private:
  bool _internal_abs_active() const;
  void _internal_set_abs_active(bool value);

  public:
  // bool traction_control = 5;
  void clear_traction_control() ;
  bool traction_control() const;
  void set_traction_control(bool value);

  private:
  bool _internal_traction_control() const;
  void _internal_set_traction_control(bool value);

  public:
  // @@protoc_insertion_point(class_scope:avisio_ivi.SafetyStatus)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SafetyStatus& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t timestamp_ms_;
    bool seatbelt_fastened_;
    bool airbag_ok_;
    bool abs_active_;
    bool traction_control_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_avisio_5fivi_5fdata_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SafetyStatus_class_data_;
// -------------------------------------------------------------------

class PrimaryVehicleState final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:avisio_ivi.PrimaryVehicleState) */ {
 public:
  inline PrimaryVehicleState() : PrimaryVehicleState(nullptr) {}
  ~PrimaryVehicleState() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PrimaryVehicleState* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PrimaryVehicleState));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PrimaryVehicleState(::google::protobuf::internal::ConstantInitialized);

  inline PrimaryVehicleState(const PrimaryVehicleState& from) : PrimaryVehicleState(nullptr, from) {}
  inline PrimaryVehicleState(PrimaryVehicleState&& from) noexcept
      : PrimaryVehicleState(nullptr, ::std::move(from)) {}
  inline PrimaryVehicleState& operator=(const PrimaryVehicleState& from) {
    CopyFrom(from);
    return *this;
  }
  inline PrimaryVehicleState& operator=(PrimaryVehicleState&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PrimaryVehicleState& default_instance() {
    return *reinterpret_cast<const PrimaryVehicleState*>(
        &_PrimaryVehicleState_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PrimaryVehicleState& a, PrimaryVehicleState& b) { a.Swap(&b); }
  inline void Swap(PrimaryVehicleState* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PrimaryVehicleState* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PrimaryVehicleState* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PrimaryVehicleState>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PrimaryVehicleState& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PrimaryVehicleState& from) { PrimaryVehicleState::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PrimaryVehicleState* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "avisio_ivi.PrimaryVehicleState"; }

 protected:
  explicit PrimaryVehicleState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PrimaryVehicleState(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PrimaryVehicleState& from);
  PrimaryVehicleState(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PrimaryVehicleState&& from) noexcept
      : PrimaryVehicleState(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTimestampMsFieldNumber = 1,
    kSpeedKmhFieldNumber = 2,
    kCurrentDriveModeFieldNumber = 3,
    kBatteryPercentFieldNumber = 4,
    kMotorTempCFieldNumber = 5,
    kOdometerKmFieldNumber = 6,
    kTripDistanceMFieldNumber = 7,
  };
  // uint32 timestamp_ms = 1;
  void clear_timestamp_ms() ;
  ::uint32_t timestamp_ms() const;
  void set_timestamp_ms(::uint32_t value);

  private:
  ::uint32_t _internal_timestamp_ms() const;
  void _internal_set_timestamp_ms(::uint32_t value);

  public:
  // float speed_kmh = 2;
  void clear_speed_kmh() ;
  float speed_kmh() const;
  void set_speed_kmh(float value);

  private:
  float _internal_speed_kmh() const;
  void _internal_set_speed_kmh(float value);

  public:
  // .avisio_ivi.DriveMode current_drive_mode = 3;
  void clear_current_drive_mode() ;
  ::avisio_ivi::DriveMode current_drive_mode() const;
  void set_current_drive_mode(::avisio_ivi::DriveMode value);

  private:
  ::avisio_ivi::DriveMode _internal_current_drive_mode() const;
  void _internal_set_current_drive_mode(::avisio_ivi::DriveMode value);

  public:
  // uint32 battery_percent = 4;
  void clear_battery_percent() ;
  ::uint32_t battery_percent() const;
  void set_battery_percent(::uint32_t value);

  private:
  ::uint32_t _internal_battery_percent() const;
  void _internal_set_battery_percent(::uint32_t value);

  public:
  // int32 motor_temp_c = 5;
  void clear_motor_temp_c() ;
  ::int32_t motor_temp_c() const;
  void set_motor_temp_c(::int32_t value);

  private:
  ::int32_t _internal_motor_temp_c() const;
  void _internal_set_motor_temp_c(::int32_t value);

  public:
  // uint32 odometer_km = 6;
  void clear_odometer_km() ;
  ::uint32_t odometer_km() const;
  void set_odometer_km(::uint32_t value);

  private:
  ::uint32_t _internal_odometer_km() const;
  void _internal_set_odometer_km(::uint32_t value);

  public:
  // uint32 trip_distance_m = 7;
  void clear_trip_distance_m() ;
  ::uint32_t trip_distance_m() const;
  void set_trip_distance_m(::uint32_t value);

  private:
  ::uint32_t _internal_trip_distance_m() const;
  void _internal_set_trip_distance_m(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:avisio_ivi.PrimaryVehicleState)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 7,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PrimaryVehicleState& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t timestamp_ms_;
    float speed_kmh_;
    int current_drive_mode_;
    ::uint32_t battery_percent_;
    ::int32_t motor_temp_c_;
    ::uint32_t odometer_km_;
    ::uint32_t trip_distance_m_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_avisio_5fivi_5fdata_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PrimaryVehicleState_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PrimaryVehicleState

// uint32 timestamp_ms = 1;
inline void PrimaryVehicleState::clear_timestamp_ms() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ms_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint32_t PrimaryVehicleState::timestamp_ms() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.PrimaryVehicleState.timestamp_ms)
  return _internal_timestamp_ms();
}
inline void PrimaryVehicleState::set_timestamp_ms(::uint32_t value) {
  _internal_set_timestamp_ms(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:avisio_ivi.PrimaryVehicleState.timestamp_ms)
}
inline ::uint32_t PrimaryVehicleState::_internal_timestamp_ms() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_ms_;
}
inline void PrimaryVehicleState::_internal_set_timestamp_ms(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ms_ = value;
}

// float speed_kmh = 2;
inline void PrimaryVehicleState::clear_speed_kmh() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.speed_kmh_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline float PrimaryVehicleState::speed_kmh() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.PrimaryVehicleState.speed_kmh)
  return _internal_speed_kmh();
}
inline void PrimaryVehicleState::set_speed_kmh(float value) {
  _internal_set_speed_kmh(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:avisio_ivi.PrimaryVehicleState.speed_kmh)
}
inline float PrimaryVehicleState::_internal_speed_kmh() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.speed_kmh_;
}
inline void PrimaryVehicleState::_internal_set_speed_kmh(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.speed_kmh_ = value;
}

// .avisio_ivi.DriveMode current_drive_mode = 3;
inline void PrimaryVehicleState::clear_current_drive_mode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.current_drive_mode_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::avisio_ivi::DriveMode PrimaryVehicleState::current_drive_mode() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.PrimaryVehicleState.current_drive_mode)
  return _internal_current_drive_mode();
}
inline void PrimaryVehicleState::set_current_drive_mode(::avisio_ivi::DriveMode value) {
  _internal_set_current_drive_mode(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:avisio_ivi.PrimaryVehicleState.current_drive_mode)
}
inline ::avisio_ivi::DriveMode PrimaryVehicleState::_internal_current_drive_mode() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::avisio_ivi::DriveMode>(_impl_.current_drive_mode_);
}
inline void PrimaryVehicleState::_internal_set_current_drive_mode(::avisio_ivi::DriveMode value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.current_drive_mode_ = value;
}

// uint32 battery_percent = 4;
inline void PrimaryVehicleState::clear_battery_percent() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.battery_percent_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::uint32_t PrimaryVehicleState::battery_percent() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.PrimaryVehicleState.battery_percent)
  return _internal_battery_percent();
}
inline void PrimaryVehicleState::set_battery_percent(::uint32_t value) {
  _internal_set_battery_percent(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:avisio_ivi.PrimaryVehicleState.battery_percent)
}
inline ::uint32_t PrimaryVehicleState::_internal_battery_percent() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.battery_percent_;
}
inline void PrimaryVehicleState::_internal_set_battery_percent(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.battery_percent_ = value;
}

// int32 motor_temp_c = 5;
inline void PrimaryVehicleState::clear_motor_temp_c() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.motor_temp_c_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::int32_t PrimaryVehicleState::motor_temp_c() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.PrimaryVehicleState.motor_temp_c)
  return _internal_motor_temp_c();
}
inline void PrimaryVehicleState::set_motor_temp_c(::int32_t value) {
  _internal_set_motor_temp_c(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:avisio_ivi.PrimaryVehicleState.motor_temp_c)
}
inline ::int32_t PrimaryVehicleState::_internal_motor_temp_c() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.motor_temp_c_;
}
inline void PrimaryVehicleState::_internal_set_motor_temp_c(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.motor_temp_c_ = value;
}

// uint32 odometer_km = 6;
inline void PrimaryVehicleState::clear_odometer_km() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.odometer_km_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline ::uint32_t PrimaryVehicleState::odometer_km() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.PrimaryVehicleState.odometer_km)
  return _internal_odometer_km();
}
inline void PrimaryVehicleState::set_odometer_km(::uint32_t value) {
  _internal_set_odometer_km(value);
  _impl_._has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_set:avisio_ivi.PrimaryVehicleState.odometer_km)
}
inline ::uint32_t PrimaryVehicleState::_internal_odometer_km() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.odometer_km_;
}
inline void PrimaryVehicleState::_internal_set_odometer_km(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.odometer_km_ = value;
}

// uint32 trip_distance_m = 7;
inline void PrimaryVehicleState::clear_trip_distance_m() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.trip_distance_m_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline ::uint32_t PrimaryVehicleState::trip_distance_m() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.PrimaryVehicleState.trip_distance_m)
  return _internal_trip_distance_m();
}
inline void PrimaryVehicleState::set_trip_distance_m(::uint32_t value) {
  _internal_set_trip_distance_m(value);
  _impl_._has_bits_[0] |= 0x00000040u;
  // @@protoc_insertion_point(field_set:avisio_ivi.PrimaryVehicleState.trip_distance_m)
}
inline ::uint32_t PrimaryVehicleState::_internal_trip_distance_m() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.trip_distance_m_;
}
inline void PrimaryVehicleState::_internal_set_trip_distance_m(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.trip_distance_m_ = value;
}

// -------------------------------------------------------------------

// SignalLightingStatus

// uint32 timestamp_ms = 1;
inline void SignalLightingStatus::clear_timestamp_ms() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ms_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint32_t SignalLightingStatus::timestamp_ms() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.SignalLightingStatus.timestamp_ms)
  return _internal_timestamp_ms();
}
inline void SignalLightingStatus::set_timestamp_ms(::uint32_t value) {
  _internal_set_timestamp_ms(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:avisio_ivi.SignalLightingStatus.timestamp_ms)
}
inline ::uint32_t SignalLightingStatus::_internal_timestamp_ms() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_ms_;
}
inline void SignalLightingStatus::_internal_set_timestamp_ms(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ms_ = value;
}

// uint32 turn_signals = 2;
inline void SignalLightingStatus::clear_turn_signals() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.turn_signals_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::uint32_t SignalLightingStatus::turn_signals() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.SignalLightingStatus.turn_signals)
  return _internal_turn_signals();
}
inline void SignalLightingStatus::set_turn_signals(::uint32_t value) {
  _internal_set_turn_signals(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:avisio_ivi.SignalLightingStatus.turn_signals)
}
inline ::uint32_t SignalLightingStatus::_internal_turn_signals() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.turn_signals_;
}
inline void SignalLightingStatus::_internal_set_turn_signals(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.turn_signals_ = value;
}

// uint32 exterior_lights = 3;
inline void SignalLightingStatus::clear_exterior_lights() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exterior_lights_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::uint32_t SignalLightingStatus::exterior_lights() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.SignalLightingStatus.exterior_lights)
  return _internal_exterior_lights();
}
inline void SignalLightingStatus::set_exterior_lights(::uint32_t value) {
  _internal_set_exterior_lights(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:avisio_ivi.SignalLightingStatus.exterior_lights)
}
inline ::uint32_t SignalLightingStatus::_internal_exterior_lights() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.exterior_lights_;
}
inline void SignalLightingStatus::_internal_set_exterior_lights(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exterior_lights_ = value;
}

// -------------------------------------------------------------------

// SafetyStatus

// uint32 timestamp_ms = 1;
inline void SafetyStatus::clear_timestamp_ms() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ms_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint32_t SafetyStatus::timestamp_ms() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.SafetyStatus.timestamp_ms)
  return _internal_timestamp_ms();
}
inline void SafetyStatus::set_timestamp_ms(::uint32_t value) {
  _internal_set_timestamp_ms(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:avisio_ivi.SafetyStatus.timestamp_ms)
}
inline ::uint32_t SafetyStatus::_internal_timestamp_ms() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_ms_;
}
inline void SafetyStatus::_internal_set_timestamp_ms(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ms_ = value;
}

// bool seatbelt_fastened = 2;
inline void SafetyStatus::clear_seatbelt_fastened() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.seatbelt_fastened_ = false;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline bool SafetyStatus::seatbelt_fastened() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.SafetyStatus.seatbelt_fastened)
  return _internal_seatbelt_fastened();
}
inline void SafetyStatus::set_seatbelt_fastened(bool value) {
  _internal_set_seatbelt_fastened(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:avisio_ivi.SafetyStatus.seatbelt_fastened)
}
inline bool SafetyStatus::_internal_seatbelt_fastened() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.seatbelt_fastened_;
}
inline void SafetyStatus::_internal_set_seatbelt_fastened(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.seatbelt_fastened_ = value;
}

// bool airbag_ok = 3;
inline void SafetyStatus::clear_airbag_ok() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.airbag_ok_ = false;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline bool SafetyStatus::airbag_ok() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.SafetyStatus.airbag_ok)
  return _internal_airbag_ok();
}
inline void SafetyStatus::set_airbag_ok(bool value) {
  _internal_set_airbag_ok(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:avisio_ivi.SafetyStatus.airbag_ok)
}
inline bool SafetyStatus::_internal_airbag_ok() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.airbag_ok_;
}
inline void SafetyStatus::_internal_set_airbag_ok(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.airbag_ok_ = value;
}

// bool abs_active = 4;
inline void SafetyStatus::clear_abs_active() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.abs_active_ = false;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline bool SafetyStatus::abs_active() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.SafetyStatus.abs_active)
  return _internal_abs_active();
}
inline void SafetyStatus::set_abs_active(bool value) {
  _internal_set_abs_active(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:avisio_ivi.SafetyStatus.abs_active)
}
inline bool SafetyStatus::_internal_abs_active() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.abs_active_;
}
inline void SafetyStatus::_internal_set_abs_active(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.abs_active_ = value;
}

// bool traction_control = 5;
inline void SafetyStatus::clear_traction_control() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.traction_control_ = false;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline bool SafetyStatus::traction_control() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.SafetyStatus.traction_control)
  return _internal_traction_control();
}
inline void SafetyStatus::set_traction_control(bool value) {
  _internal_set_traction_control(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:avisio_ivi.SafetyStatus.traction_control)
}
inline bool SafetyStatus::_internal_traction_control() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.traction_control_;
}
inline void SafetyStatus::_internal_set_traction_control(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.traction_control_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace avisio_ivi


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::avisio_ivi::DriveMode> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::avisio_ivi::DriveMode>() {
  return ::avisio_ivi::DriveMode_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // avisio_5fivi_5fdata_2eproto_2epb_2eh
