// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: avisio_ivi_data.proto
// Protobuf Java Version: 4.31.0

package avisio_ivi;

@com.google.protobuf.Generated
public final class AvisioIviData {
  private AvisioIviData() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 0,
      /* suffix= */ "",
      AvisioIviData.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * Enum for EV drive selector modes
   * </pre>
   *
   * Protobuf enum {@code avisio_ivi.DriveMode}
   */
  public enum DriveMode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DRIVE_MODE_PARK = 0;</code>
     */
    DRIVE_MODE_PARK(0),
    /**
     * <code>DRIVE_MODE_REVERSE = 1;</code>
     */
    DRIVE_MODE_REVERSE(1),
    /**
     * <code>DRIVE_MODE_NEUTRAL = 2;</code>
     */
    DRIVE_MODE_NEUTRAL(2),
    /**
     * <code>DRIVE_MODE_DRIVE = 3;</code>
     */
    DRIVE_MODE_DRIVE(3),
    /**
     * <pre>
     * Optional: Regenerative braking mode
     * </pre>
     *
     * <code>DRIVE_MODE_BRAKE = 4;</code>
     */
    DRIVE_MODE_BRAKE(4),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 0,
        /* suffix= */ "",
        DriveMode.class.getName());
    }
    /**
     * <code>DRIVE_MODE_PARK = 0;</code>
     */
    public static final int DRIVE_MODE_PARK_VALUE = 0;
    /**
     * <code>DRIVE_MODE_REVERSE = 1;</code>
     */
    public static final int DRIVE_MODE_REVERSE_VALUE = 1;
    /**
     * <code>DRIVE_MODE_NEUTRAL = 2;</code>
     */
    public static final int DRIVE_MODE_NEUTRAL_VALUE = 2;
    /**
     * <code>DRIVE_MODE_DRIVE = 3;</code>
     */
    public static final int DRIVE_MODE_DRIVE_VALUE = 3;
    /**
     * <pre>
     * Optional: Regenerative braking mode
     * </pre>
     *
     * <code>DRIVE_MODE_BRAKE = 4;</code>
     */
    public static final int DRIVE_MODE_BRAKE_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DriveMode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DriveMode forNumber(int value) {
      switch (value) {
        case 0: return DRIVE_MODE_PARK;
        case 1: return DRIVE_MODE_REVERSE;
        case 2: return DRIVE_MODE_NEUTRAL;
        case 3: return DRIVE_MODE_DRIVE;
        case 4: return DRIVE_MODE_BRAKE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DriveMode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DriveMode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DriveMode>() {
            public DriveMode findValueByNumber(int number) {
              return DriveMode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return avisio_ivi.AvisioIviData.getDescriptor().getEnumTypes().get(0);
    }

    private static final DriveMode[] VALUES = values();

    public static DriveMode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DriveMode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:avisio_ivi.DriveMode)
  }

  public interface PrimaryVehicleStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:avisio_ivi.PrimaryVehicleState)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 timestamp_ms = 1;</code>
     * @return The timestampMs.
     */
    int getTimestampMs();

    /**
     * <code>float speed_kmh = 2;</code>
     * @return The speedKmh.
     */
    float getSpeedKmh();

    /**
     * <code>.avisio_ivi.DriveMode current_drive_mode = 3;</code>
     * @return The enum numeric value on the wire for currentDriveMode.
     */
    int getCurrentDriveModeValue();
    /**
     * <code>.avisio_ivi.DriveMode current_drive_mode = 3;</code>
     * @return The currentDriveMode.
     */
    avisio_ivi.AvisioIviData.DriveMode getCurrentDriveMode();

    /**
     * <pre>
     * Battery SoC (0–100%)
     * </pre>
     *
     * <code>uint32 battery_percent = 4;</code>
     * @return The batteryPercent.
     */
    int getBatteryPercent();

    /**
     * <pre>
     * Electric motor or controller temp
     * </pre>
     *
     * <code>int32 motor_temp_c = 5;</code>
     * @return The motorTempC.
     */
    int getMotorTempC();

    /**
     * <code>uint32 odometer_km = 6;</code>
     * @return The odometerKm.
     */
    int getOdometerKm();

    /**
     * <code>uint32 trip_distance_m = 7;</code>
     * @return The tripDistanceM.
     */
    int getTripDistanceM();
  }
  /**
   * <pre>
   * Vehicle Primary State (core EV metrics)
   * </pre>
   *
   * Protobuf type {@code avisio_ivi.PrimaryVehicleState}
   */
  public static final class PrimaryVehicleState extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:avisio_ivi.PrimaryVehicleState)
      PrimaryVehicleStateOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 0,
        /* suffix= */ "",
        PrimaryVehicleState.class.getName());
    }
    // Use PrimaryVehicleState.newBuilder() to construct.
    private PrimaryVehicleState(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PrimaryVehicleState() {
      currentDriveMode_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return avisio_ivi.AvisioIviData.internal_static_avisio_ivi_PrimaryVehicleState_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return avisio_ivi.AvisioIviData.internal_static_avisio_ivi_PrimaryVehicleState_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              avisio_ivi.AvisioIviData.PrimaryVehicleState.class, avisio_ivi.AvisioIviData.PrimaryVehicleState.Builder.class);
    }

    public static final int TIMESTAMP_MS_FIELD_NUMBER = 1;
    private int timestampMs_ = 0;
    /**
     * <code>uint32 timestamp_ms = 1;</code>
     * @return The timestampMs.
     */
    @java.lang.Override
    public int getTimestampMs() {
      return timestampMs_;
    }

    public static final int SPEED_KMH_FIELD_NUMBER = 2;
    private float speedKmh_ = 0F;
    /**
     * <code>float speed_kmh = 2;</code>
     * @return The speedKmh.
     */
    @java.lang.Override
    public float getSpeedKmh() {
      return speedKmh_;
    }

    public static final int CURRENT_DRIVE_MODE_FIELD_NUMBER = 3;
    private int currentDriveMode_ = 0;
    /**
     * <code>.avisio_ivi.DriveMode current_drive_mode = 3;</code>
     * @return The enum numeric value on the wire for currentDriveMode.
     */
    @java.lang.Override public int getCurrentDriveModeValue() {
      return currentDriveMode_;
    }
    /**
     * <code>.avisio_ivi.DriveMode current_drive_mode = 3;</code>
     * @return The currentDriveMode.
     */
    @java.lang.Override public avisio_ivi.AvisioIviData.DriveMode getCurrentDriveMode() {
      avisio_ivi.AvisioIviData.DriveMode result = avisio_ivi.AvisioIviData.DriveMode.forNumber(currentDriveMode_);
      return result == null ? avisio_ivi.AvisioIviData.DriveMode.UNRECOGNIZED : result;
    }

    public static final int BATTERY_PERCENT_FIELD_NUMBER = 4;
    private int batteryPercent_ = 0;
    /**
     * <pre>
     * Battery SoC (0–100%)
     * </pre>
     *
     * <code>uint32 battery_percent = 4;</code>
     * @return The batteryPercent.
     */
    @java.lang.Override
    public int getBatteryPercent() {
      return batteryPercent_;
    }

    public static final int MOTOR_TEMP_C_FIELD_NUMBER = 5;
    private int motorTempC_ = 0;
    /**
     * <pre>
     * Electric motor or controller temp
     * </pre>
     *
     * <code>int32 motor_temp_c = 5;</code>
     * @return The motorTempC.
     */
    @java.lang.Override
    public int getMotorTempC() {
      return motorTempC_;
    }

    public static final int ODOMETER_KM_FIELD_NUMBER = 6;
    private int odometerKm_ = 0;
    /**
     * <code>uint32 odometer_km = 6;</code>
     * @return The odometerKm.
     */
    @java.lang.Override
    public int getOdometerKm() {
      return odometerKm_;
    }

    public static final int TRIP_DISTANCE_M_FIELD_NUMBER = 7;
    private int tripDistanceM_ = 0;
    /**
     * <code>uint32 trip_distance_m = 7;</code>
     * @return The tripDistanceM.
     */
    @java.lang.Override
    public int getTripDistanceM() {
      return tripDistanceM_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestampMs_ != 0) {
        output.writeUInt32(1, timestampMs_);
      }
      if (java.lang.Float.floatToRawIntBits(speedKmh_) != 0) {
        output.writeFloat(2, speedKmh_);
      }
      if (currentDriveMode_ != avisio_ivi.AvisioIviData.DriveMode.DRIVE_MODE_PARK.getNumber()) {
        output.writeEnum(3, currentDriveMode_);
      }
      if (batteryPercent_ != 0) {
        output.writeUInt32(4, batteryPercent_);
      }
      if (motorTempC_ != 0) {
        output.writeInt32(5, motorTempC_);
      }
      if (odometerKm_ != 0) {
        output.writeUInt32(6, odometerKm_);
      }
      if (tripDistanceM_ != 0) {
        output.writeUInt32(7, tripDistanceM_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestampMs_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, timestampMs_);
      }
      if (java.lang.Float.floatToRawIntBits(speedKmh_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, speedKmh_);
      }
      if (currentDriveMode_ != avisio_ivi.AvisioIviData.DriveMode.DRIVE_MODE_PARK.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, currentDriveMode_);
      }
      if (batteryPercent_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, batteryPercent_);
      }
      if (motorTempC_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, motorTempC_);
      }
      if (odometerKm_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, odometerKm_);
      }
      if (tripDistanceM_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, tripDistanceM_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof avisio_ivi.AvisioIviData.PrimaryVehicleState)) {
        return super.equals(obj);
      }
      avisio_ivi.AvisioIviData.PrimaryVehicleState other = (avisio_ivi.AvisioIviData.PrimaryVehicleState) obj;

      if (getTimestampMs()
          != other.getTimestampMs()) return false;
      if (java.lang.Float.floatToIntBits(getSpeedKmh())
          != java.lang.Float.floatToIntBits(
              other.getSpeedKmh())) return false;
      if (currentDriveMode_ != other.currentDriveMode_) return false;
      if (getBatteryPercent()
          != other.getBatteryPercent()) return false;
      if (getMotorTempC()
          != other.getMotorTempC()) return false;
      if (getOdometerKm()
          != other.getOdometerKm()) return false;
      if (getTripDistanceM()
          != other.getTripDistanceM()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_MS_FIELD_NUMBER;
      hash = (53 * hash) + getTimestampMs();
      hash = (37 * hash) + SPEED_KMH_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getSpeedKmh());
      hash = (37 * hash) + CURRENT_DRIVE_MODE_FIELD_NUMBER;
      hash = (53 * hash) + currentDriveMode_;
      hash = (37 * hash) + BATTERY_PERCENT_FIELD_NUMBER;
      hash = (53 * hash) + getBatteryPercent();
      hash = (37 * hash) + MOTOR_TEMP_C_FIELD_NUMBER;
      hash = (53 * hash) + getMotorTempC();
      hash = (37 * hash) + ODOMETER_KM_FIELD_NUMBER;
      hash = (53 * hash) + getOdometerKm();
      hash = (37 * hash) + TRIP_DISTANCE_M_FIELD_NUMBER;
      hash = (53 * hash) + getTripDistanceM();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static avisio_ivi.AvisioIviData.PrimaryVehicleState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static avisio_ivi.AvisioIviData.PrimaryVehicleState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static avisio_ivi.AvisioIviData.PrimaryVehicleState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static avisio_ivi.AvisioIviData.PrimaryVehicleState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static avisio_ivi.AvisioIviData.PrimaryVehicleState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static avisio_ivi.AvisioIviData.PrimaryVehicleState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static avisio_ivi.AvisioIviData.PrimaryVehicleState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static avisio_ivi.AvisioIviData.PrimaryVehicleState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static avisio_ivi.AvisioIviData.PrimaryVehicleState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static avisio_ivi.AvisioIviData.PrimaryVehicleState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static avisio_ivi.AvisioIviData.PrimaryVehicleState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static avisio_ivi.AvisioIviData.PrimaryVehicleState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(avisio_ivi.AvisioIviData.PrimaryVehicleState prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Vehicle Primary State (core EV metrics)
     * </pre>
     *
     * Protobuf type {@code avisio_ivi.PrimaryVehicleState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:avisio_ivi.PrimaryVehicleState)
        avisio_ivi.AvisioIviData.PrimaryVehicleStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return avisio_ivi.AvisioIviData.internal_static_avisio_ivi_PrimaryVehicleState_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return avisio_ivi.AvisioIviData.internal_static_avisio_ivi_PrimaryVehicleState_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                avisio_ivi.AvisioIviData.PrimaryVehicleState.class, avisio_ivi.AvisioIviData.PrimaryVehicleState.Builder.class);
      }

      // Construct using avisio_ivi.AvisioIviData.PrimaryVehicleState.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        timestampMs_ = 0;
        speedKmh_ = 0F;
        currentDriveMode_ = 0;
        batteryPercent_ = 0;
        motorTempC_ = 0;
        odometerKm_ = 0;
        tripDistanceM_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return avisio_ivi.AvisioIviData.internal_static_avisio_ivi_PrimaryVehicleState_descriptor;
      }

      @java.lang.Override
      public avisio_ivi.AvisioIviData.PrimaryVehicleState getDefaultInstanceForType() {
        return avisio_ivi.AvisioIviData.PrimaryVehicleState.getDefaultInstance();
      }

      @java.lang.Override
      public avisio_ivi.AvisioIviData.PrimaryVehicleState build() {
        avisio_ivi.AvisioIviData.PrimaryVehicleState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public avisio_ivi.AvisioIviData.PrimaryVehicleState buildPartial() {
        avisio_ivi.AvisioIviData.PrimaryVehicleState result = new avisio_ivi.AvisioIviData.PrimaryVehicleState(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(avisio_ivi.AvisioIviData.PrimaryVehicleState result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timestampMs_ = timestampMs_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.speedKmh_ = speedKmh_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.currentDriveMode_ = currentDriveMode_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.batteryPercent_ = batteryPercent_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.motorTempC_ = motorTempC_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.odometerKm_ = odometerKm_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.tripDistanceM_ = tripDistanceM_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof avisio_ivi.AvisioIviData.PrimaryVehicleState) {
          return mergeFrom((avisio_ivi.AvisioIviData.PrimaryVehicleState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(avisio_ivi.AvisioIviData.PrimaryVehicleState other) {
        if (other == avisio_ivi.AvisioIviData.PrimaryVehicleState.getDefaultInstance()) return this;
        if (other.getTimestampMs() != 0) {
          setTimestampMs(other.getTimestampMs());
        }
        if (java.lang.Float.floatToRawIntBits(other.getSpeedKmh()) != 0) {
          setSpeedKmh(other.getSpeedKmh());
        }
        if (other.currentDriveMode_ != 0) {
          setCurrentDriveModeValue(other.getCurrentDriveModeValue());
        }
        if (other.getBatteryPercent() != 0) {
          setBatteryPercent(other.getBatteryPercent());
        }
        if (other.getMotorTempC() != 0) {
          setMotorTempC(other.getMotorTempC());
        }
        if (other.getOdometerKm() != 0) {
          setOdometerKm(other.getOdometerKm());
        }
        if (other.getTripDistanceM() != 0) {
          setTripDistanceM(other.getTripDistanceM());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                timestampMs_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 21: {
                speedKmh_ = input.readFloat();
                bitField0_ |= 0x00000002;
                break;
              } // case 21
              case 24: {
                currentDriveMode_ = input.readEnum();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                batteryPercent_ = input.readUInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                motorTempC_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                odometerKm_ = input.readUInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                tripDistanceM_ = input.readUInt32();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int timestampMs_ ;
      /**
       * <code>uint32 timestamp_ms = 1;</code>
       * @return The timestampMs.
       */
      @java.lang.Override
      public int getTimestampMs() {
        return timestampMs_;
      }
      /**
       * <code>uint32 timestamp_ms = 1;</code>
       * @param value The timestampMs to set.
       * @return This builder for chaining.
       */
      public Builder setTimestampMs(int value) {

        timestampMs_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 timestamp_ms = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestampMs() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestampMs_ = 0;
        onChanged();
        return this;
      }

      private float speedKmh_ ;
      /**
       * <code>float speed_kmh = 2;</code>
       * @return The speedKmh.
       */
      @java.lang.Override
      public float getSpeedKmh() {
        return speedKmh_;
      }
      /**
       * <code>float speed_kmh = 2;</code>
       * @param value The speedKmh to set.
       * @return This builder for chaining.
       */
      public Builder setSpeedKmh(float value) {

        speedKmh_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>float speed_kmh = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSpeedKmh() {
        bitField0_ = (bitField0_ & ~0x00000002);
        speedKmh_ = 0F;
        onChanged();
        return this;
      }

      private int currentDriveMode_ = 0;
      /**
       * <code>.avisio_ivi.DriveMode current_drive_mode = 3;</code>
       * @return The enum numeric value on the wire for currentDriveMode.
       */
      @java.lang.Override public int getCurrentDriveModeValue() {
        return currentDriveMode_;
      }
      /**
       * <code>.avisio_ivi.DriveMode current_drive_mode = 3;</code>
       * @param value The enum numeric value on the wire for currentDriveMode to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentDriveModeValue(int value) {
        currentDriveMode_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.avisio_ivi.DriveMode current_drive_mode = 3;</code>
       * @return The currentDriveMode.
       */
      @java.lang.Override
      public avisio_ivi.AvisioIviData.DriveMode getCurrentDriveMode() {
        avisio_ivi.AvisioIviData.DriveMode result = avisio_ivi.AvisioIviData.DriveMode.forNumber(currentDriveMode_);
        return result == null ? avisio_ivi.AvisioIviData.DriveMode.UNRECOGNIZED : result;
      }
      /**
       * <code>.avisio_ivi.DriveMode current_drive_mode = 3;</code>
       * @param value The currentDriveMode to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentDriveMode(avisio_ivi.AvisioIviData.DriveMode value) {
        if (value == null) { throw new NullPointerException(); }
        bitField0_ |= 0x00000004;
        currentDriveMode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.avisio_ivi.DriveMode current_drive_mode = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentDriveMode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        currentDriveMode_ = 0;
        onChanged();
        return this;
      }

      private int batteryPercent_ ;
      /**
       * <pre>
       * Battery SoC (0–100%)
       * </pre>
       *
       * <code>uint32 battery_percent = 4;</code>
       * @return The batteryPercent.
       */
      @java.lang.Override
      public int getBatteryPercent() {
        return batteryPercent_;
      }
      /**
       * <pre>
       * Battery SoC (0–100%)
       * </pre>
       *
       * <code>uint32 battery_percent = 4;</code>
       * @param value The batteryPercent to set.
       * @return This builder for chaining.
       */
      public Builder setBatteryPercent(int value) {

        batteryPercent_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Battery SoC (0–100%)
       * </pre>
       *
       * <code>uint32 battery_percent = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBatteryPercent() {
        bitField0_ = (bitField0_ & ~0x00000008);
        batteryPercent_ = 0;
        onChanged();
        return this;
      }

      private int motorTempC_ ;
      /**
       * <pre>
       * Electric motor or controller temp
       * </pre>
       *
       * <code>int32 motor_temp_c = 5;</code>
       * @return The motorTempC.
       */
      @java.lang.Override
      public int getMotorTempC() {
        return motorTempC_;
      }
      /**
       * <pre>
       * Electric motor or controller temp
       * </pre>
       *
       * <code>int32 motor_temp_c = 5;</code>
       * @param value The motorTempC to set.
       * @return This builder for chaining.
       */
      public Builder setMotorTempC(int value) {

        motorTempC_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Electric motor or controller temp
       * </pre>
       *
       * <code>int32 motor_temp_c = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMotorTempC() {
        bitField0_ = (bitField0_ & ~0x00000010);
        motorTempC_ = 0;
        onChanged();
        return this;
      }

      private int odometerKm_ ;
      /**
       * <code>uint32 odometer_km = 6;</code>
       * @return The odometerKm.
       */
      @java.lang.Override
      public int getOdometerKm() {
        return odometerKm_;
      }
      /**
       * <code>uint32 odometer_km = 6;</code>
       * @param value The odometerKm to set.
       * @return This builder for chaining.
       */
      public Builder setOdometerKm(int value) {

        odometerKm_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 odometer_km = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearOdometerKm() {
        bitField0_ = (bitField0_ & ~0x00000020);
        odometerKm_ = 0;
        onChanged();
        return this;
      }

      private int tripDistanceM_ ;
      /**
       * <code>uint32 trip_distance_m = 7;</code>
       * @return The tripDistanceM.
       */
      @java.lang.Override
      public int getTripDistanceM() {
        return tripDistanceM_;
      }
      /**
       * <code>uint32 trip_distance_m = 7;</code>
       * @param value The tripDistanceM to set.
       * @return This builder for chaining.
       */
      public Builder setTripDistanceM(int value) {

        tripDistanceM_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 trip_distance_m = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearTripDistanceM() {
        bitField0_ = (bitField0_ & ~0x00000040);
        tripDistanceM_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:avisio_ivi.PrimaryVehicleState)
    }

    // @@protoc_insertion_point(class_scope:avisio_ivi.PrimaryVehicleState)
    private static final avisio_ivi.AvisioIviData.PrimaryVehicleState DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new avisio_ivi.AvisioIviData.PrimaryVehicleState();
    }

    public static avisio_ivi.AvisioIviData.PrimaryVehicleState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PrimaryVehicleState>
        PARSER = new com.google.protobuf.AbstractParser<PrimaryVehicleState>() {
      @java.lang.Override
      public PrimaryVehicleState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PrimaryVehicleState> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PrimaryVehicleState> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public avisio_ivi.AvisioIviData.PrimaryVehicleState getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SignalLightingStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:avisio_ivi.SignalLightingStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 timestamp_ms = 1;</code>
     * @return The timestampMs.
     */
    int getTimestampMs();

    /**
     * <pre>
     * Bitfield: bit 0 = left, 1 = right, 2 = hazard
     * </pre>
     *
     * <code>uint32 turn_signals = 2;</code>
     * @return The turnSignals.
     */
    int getTurnSignals();

    /**
     * <pre>
     * Bitfield: headlights, fog lights, etc.
     * </pre>
     *
     * <code>uint32 exterior_lights = 3;</code>
     * @return The exteriorLights.
     */
    int getExteriorLights();
  }
  /**
   * <pre>
   * Lighting and turn signal info
   * </pre>
   *
   * Protobuf type {@code avisio_ivi.SignalLightingStatus}
   */
  public static final class SignalLightingStatus extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:avisio_ivi.SignalLightingStatus)
      SignalLightingStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 0,
        /* suffix= */ "",
        SignalLightingStatus.class.getName());
    }
    // Use SignalLightingStatus.newBuilder() to construct.
    private SignalLightingStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SignalLightingStatus() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return avisio_ivi.AvisioIviData.internal_static_avisio_ivi_SignalLightingStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return avisio_ivi.AvisioIviData.internal_static_avisio_ivi_SignalLightingStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              avisio_ivi.AvisioIviData.SignalLightingStatus.class, avisio_ivi.AvisioIviData.SignalLightingStatus.Builder.class);
    }

    public static final int TIMESTAMP_MS_FIELD_NUMBER = 1;
    private int timestampMs_ = 0;
    /**
     * <code>uint32 timestamp_ms = 1;</code>
     * @return The timestampMs.
     */
    @java.lang.Override
    public int getTimestampMs() {
      return timestampMs_;
    }

    public static final int TURN_SIGNALS_FIELD_NUMBER = 2;
    private int turnSignals_ = 0;
    /**
     * <pre>
     * Bitfield: bit 0 = left, 1 = right, 2 = hazard
     * </pre>
     *
     * <code>uint32 turn_signals = 2;</code>
     * @return The turnSignals.
     */
    @java.lang.Override
    public int getTurnSignals() {
      return turnSignals_;
    }

    public static final int EXTERIOR_LIGHTS_FIELD_NUMBER = 3;
    private int exteriorLights_ = 0;
    /**
     * <pre>
     * Bitfield: headlights, fog lights, etc.
     * </pre>
     *
     * <code>uint32 exterior_lights = 3;</code>
     * @return The exteriorLights.
     */
    @java.lang.Override
    public int getExteriorLights() {
      return exteriorLights_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestampMs_ != 0) {
        output.writeUInt32(1, timestampMs_);
      }
      if (turnSignals_ != 0) {
        output.writeUInt32(2, turnSignals_);
      }
      if (exteriorLights_ != 0) {
        output.writeUInt32(3, exteriorLights_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestampMs_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, timestampMs_);
      }
      if (turnSignals_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, turnSignals_);
      }
      if (exteriorLights_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, exteriorLights_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof avisio_ivi.AvisioIviData.SignalLightingStatus)) {
        return super.equals(obj);
      }
      avisio_ivi.AvisioIviData.SignalLightingStatus other = (avisio_ivi.AvisioIviData.SignalLightingStatus) obj;

      if (getTimestampMs()
          != other.getTimestampMs()) return false;
      if (getTurnSignals()
          != other.getTurnSignals()) return false;
      if (getExteriorLights()
          != other.getExteriorLights()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_MS_FIELD_NUMBER;
      hash = (53 * hash) + getTimestampMs();
      hash = (37 * hash) + TURN_SIGNALS_FIELD_NUMBER;
      hash = (53 * hash) + getTurnSignals();
      hash = (37 * hash) + EXTERIOR_LIGHTS_FIELD_NUMBER;
      hash = (53 * hash) + getExteriorLights();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static avisio_ivi.AvisioIviData.SignalLightingStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static avisio_ivi.AvisioIviData.SignalLightingStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static avisio_ivi.AvisioIviData.SignalLightingStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static avisio_ivi.AvisioIviData.SignalLightingStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static avisio_ivi.AvisioIviData.SignalLightingStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static avisio_ivi.AvisioIviData.SignalLightingStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static avisio_ivi.AvisioIviData.SignalLightingStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static avisio_ivi.AvisioIviData.SignalLightingStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static avisio_ivi.AvisioIviData.SignalLightingStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static avisio_ivi.AvisioIviData.SignalLightingStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static avisio_ivi.AvisioIviData.SignalLightingStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static avisio_ivi.AvisioIviData.SignalLightingStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(avisio_ivi.AvisioIviData.SignalLightingStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Lighting and turn signal info
     * </pre>
     *
     * Protobuf type {@code avisio_ivi.SignalLightingStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:avisio_ivi.SignalLightingStatus)
        avisio_ivi.AvisioIviData.SignalLightingStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return avisio_ivi.AvisioIviData.internal_static_avisio_ivi_SignalLightingStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return avisio_ivi.AvisioIviData.internal_static_avisio_ivi_SignalLightingStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                avisio_ivi.AvisioIviData.SignalLightingStatus.class, avisio_ivi.AvisioIviData.SignalLightingStatus.Builder.class);
      }

      // Construct using avisio_ivi.AvisioIviData.SignalLightingStatus.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        timestampMs_ = 0;
        turnSignals_ = 0;
        exteriorLights_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return avisio_ivi.AvisioIviData.internal_static_avisio_ivi_SignalLightingStatus_descriptor;
      }

      @java.lang.Override
      public avisio_ivi.AvisioIviData.SignalLightingStatus getDefaultInstanceForType() {
        return avisio_ivi.AvisioIviData.SignalLightingStatus.getDefaultInstance();
      }

      @java.lang.Override
      public avisio_ivi.AvisioIviData.SignalLightingStatus build() {
        avisio_ivi.AvisioIviData.SignalLightingStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public avisio_ivi.AvisioIviData.SignalLightingStatus buildPartial() {
        avisio_ivi.AvisioIviData.SignalLightingStatus result = new avisio_ivi.AvisioIviData.SignalLightingStatus(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(avisio_ivi.AvisioIviData.SignalLightingStatus result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timestampMs_ = timestampMs_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.turnSignals_ = turnSignals_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.exteriorLights_ = exteriorLights_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof avisio_ivi.AvisioIviData.SignalLightingStatus) {
          return mergeFrom((avisio_ivi.AvisioIviData.SignalLightingStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(avisio_ivi.AvisioIviData.SignalLightingStatus other) {
        if (other == avisio_ivi.AvisioIviData.SignalLightingStatus.getDefaultInstance()) return this;
        if (other.getTimestampMs() != 0) {
          setTimestampMs(other.getTimestampMs());
        }
        if (other.getTurnSignals() != 0) {
          setTurnSignals(other.getTurnSignals());
        }
        if (other.getExteriorLights() != 0) {
          setExteriorLights(other.getExteriorLights());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                timestampMs_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                turnSignals_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                exteriorLights_ = input.readUInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int timestampMs_ ;
      /**
       * <code>uint32 timestamp_ms = 1;</code>
       * @return The timestampMs.
       */
      @java.lang.Override
      public int getTimestampMs() {
        return timestampMs_;
      }
      /**
       * <code>uint32 timestamp_ms = 1;</code>
       * @param value The timestampMs to set.
       * @return This builder for chaining.
       */
      public Builder setTimestampMs(int value) {

        timestampMs_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 timestamp_ms = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestampMs() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestampMs_ = 0;
        onChanged();
        return this;
      }

      private int turnSignals_ ;
      /**
       * <pre>
       * Bitfield: bit 0 = left, 1 = right, 2 = hazard
       * </pre>
       *
       * <code>uint32 turn_signals = 2;</code>
       * @return The turnSignals.
       */
      @java.lang.Override
      public int getTurnSignals() {
        return turnSignals_;
      }
      /**
       * <pre>
       * Bitfield: bit 0 = left, 1 = right, 2 = hazard
       * </pre>
       *
       * <code>uint32 turn_signals = 2;</code>
       * @param value The turnSignals to set.
       * @return This builder for chaining.
       */
      public Builder setTurnSignals(int value) {

        turnSignals_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Bitfield: bit 0 = left, 1 = right, 2 = hazard
       * </pre>
       *
       * <code>uint32 turn_signals = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTurnSignals() {
        bitField0_ = (bitField0_ & ~0x00000002);
        turnSignals_ = 0;
        onChanged();
        return this;
      }

      private int exteriorLights_ ;
      /**
       * <pre>
       * Bitfield: headlights, fog lights, etc.
       * </pre>
       *
       * <code>uint32 exterior_lights = 3;</code>
       * @return The exteriorLights.
       */
      @java.lang.Override
      public int getExteriorLights() {
        return exteriorLights_;
      }
      /**
       * <pre>
       * Bitfield: headlights, fog lights, etc.
       * </pre>
       *
       * <code>uint32 exterior_lights = 3;</code>
       * @param value The exteriorLights to set.
       * @return This builder for chaining.
       */
      public Builder setExteriorLights(int value) {

        exteriorLights_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Bitfield: headlights, fog lights, etc.
       * </pre>
       *
       * <code>uint32 exterior_lights = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearExteriorLights() {
        bitField0_ = (bitField0_ & ~0x00000004);
        exteriorLights_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:avisio_ivi.SignalLightingStatus)
    }

    // @@protoc_insertion_point(class_scope:avisio_ivi.SignalLightingStatus)
    private static final avisio_ivi.AvisioIviData.SignalLightingStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new avisio_ivi.AvisioIviData.SignalLightingStatus();
    }

    public static avisio_ivi.AvisioIviData.SignalLightingStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SignalLightingStatus>
        PARSER = new com.google.protobuf.AbstractParser<SignalLightingStatus>() {
      @java.lang.Override
      public SignalLightingStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SignalLightingStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SignalLightingStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public avisio_ivi.AvisioIviData.SignalLightingStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SafetyStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:avisio_ivi.SafetyStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 timestamp_ms = 1;</code>
     * @return The timestampMs.
     */
    int getTimestampMs();

    /**
     * <code>bool seatbelt_fastened = 2;</code>
     * @return The seatbeltFastened.
     */
    boolean getSeatbeltFastened();

    /**
     * <code>bool airbag_ok = 3;</code>
     * @return The airbagOk.
     */
    boolean getAirbagOk();

    /**
     * <code>bool abs_active = 4;</code>
     * @return The absActive.
     */
    boolean getAbsActive();

    /**
     * <code>bool traction_control = 5;</code>
     * @return The tractionControl.
     */
    boolean getTractionControl();
  }
  /**
   * <pre>
   * Safety &amp; status info
   * </pre>
   *
   * Protobuf type {@code avisio_ivi.SafetyStatus}
   */
  public static final class SafetyStatus extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:avisio_ivi.SafetyStatus)
      SafetyStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 0,
        /* suffix= */ "",
        SafetyStatus.class.getName());
    }
    // Use SafetyStatus.newBuilder() to construct.
    private SafetyStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SafetyStatus() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return avisio_ivi.AvisioIviData.internal_static_avisio_ivi_SafetyStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return avisio_ivi.AvisioIviData.internal_static_avisio_ivi_SafetyStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              avisio_ivi.AvisioIviData.SafetyStatus.class, avisio_ivi.AvisioIviData.SafetyStatus.Builder.class);
    }

    public static final int TIMESTAMP_MS_FIELD_NUMBER = 1;
    private int timestampMs_ = 0;
    /**
     * <code>uint32 timestamp_ms = 1;</code>
     * @return The timestampMs.
     */
    @java.lang.Override
    public int getTimestampMs() {
      return timestampMs_;
    }

    public static final int SEATBELT_FASTENED_FIELD_NUMBER = 2;
    private boolean seatbeltFastened_ = false;
    /**
     * <code>bool seatbelt_fastened = 2;</code>
     * @return The seatbeltFastened.
     */
    @java.lang.Override
    public boolean getSeatbeltFastened() {
      return seatbeltFastened_;
    }

    public static final int AIRBAG_OK_FIELD_NUMBER = 3;
    private boolean airbagOk_ = false;
    /**
     * <code>bool airbag_ok = 3;</code>
     * @return The airbagOk.
     */
    @java.lang.Override
    public boolean getAirbagOk() {
      return airbagOk_;
    }

    public static final int ABS_ACTIVE_FIELD_NUMBER = 4;
    private boolean absActive_ = false;
    /**
     * <code>bool abs_active = 4;</code>
     * @return The absActive.
     */
    @java.lang.Override
    public boolean getAbsActive() {
      return absActive_;
    }

    public static final int TRACTION_CONTROL_FIELD_NUMBER = 5;
    private boolean tractionControl_ = false;
    /**
     * <code>bool traction_control = 5;</code>
     * @return The tractionControl.
     */
    @java.lang.Override
    public boolean getTractionControl() {
      return tractionControl_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestampMs_ != 0) {
        output.writeUInt32(1, timestampMs_);
      }
      if (seatbeltFastened_ != false) {
        output.writeBool(2, seatbeltFastened_);
      }
      if (airbagOk_ != false) {
        output.writeBool(3, airbagOk_);
      }
      if (absActive_ != false) {
        output.writeBool(4, absActive_);
      }
      if (tractionControl_ != false) {
        output.writeBool(5, tractionControl_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestampMs_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, timestampMs_);
      }
      if (seatbeltFastened_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, seatbeltFastened_);
      }
      if (airbagOk_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, airbagOk_);
      }
      if (absActive_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, absActive_);
      }
      if (tractionControl_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, tractionControl_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof avisio_ivi.AvisioIviData.SafetyStatus)) {
        return super.equals(obj);
      }
      avisio_ivi.AvisioIviData.SafetyStatus other = (avisio_ivi.AvisioIviData.SafetyStatus) obj;

      if (getTimestampMs()
          != other.getTimestampMs()) return false;
      if (getSeatbeltFastened()
          != other.getSeatbeltFastened()) return false;
      if (getAirbagOk()
          != other.getAirbagOk()) return false;
      if (getAbsActive()
          != other.getAbsActive()) return false;
      if (getTractionControl()
          != other.getTractionControl()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_MS_FIELD_NUMBER;
      hash = (53 * hash) + getTimestampMs();
      hash = (37 * hash) + SEATBELT_FASTENED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSeatbeltFastened());
      hash = (37 * hash) + AIRBAG_OK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAirbagOk());
      hash = (37 * hash) + ABS_ACTIVE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAbsActive());
      hash = (37 * hash) + TRACTION_CONTROL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getTractionControl());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static avisio_ivi.AvisioIviData.SafetyStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static avisio_ivi.AvisioIviData.SafetyStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static avisio_ivi.AvisioIviData.SafetyStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static avisio_ivi.AvisioIviData.SafetyStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static avisio_ivi.AvisioIviData.SafetyStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static avisio_ivi.AvisioIviData.SafetyStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static avisio_ivi.AvisioIviData.SafetyStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static avisio_ivi.AvisioIviData.SafetyStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static avisio_ivi.AvisioIviData.SafetyStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static avisio_ivi.AvisioIviData.SafetyStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static avisio_ivi.AvisioIviData.SafetyStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static avisio_ivi.AvisioIviData.SafetyStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(avisio_ivi.AvisioIviData.SafetyStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Safety &amp; status info
     * </pre>
     *
     * Protobuf type {@code avisio_ivi.SafetyStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:avisio_ivi.SafetyStatus)
        avisio_ivi.AvisioIviData.SafetyStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return avisio_ivi.AvisioIviData.internal_static_avisio_ivi_SafetyStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return avisio_ivi.AvisioIviData.internal_static_avisio_ivi_SafetyStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                avisio_ivi.AvisioIviData.SafetyStatus.class, avisio_ivi.AvisioIviData.SafetyStatus.Builder.class);
      }

      // Construct using avisio_ivi.AvisioIviData.SafetyStatus.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        timestampMs_ = 0;
        seatbeltFastened_ = false;
        airbagOk_ = false;
        absActive_ = false;
        tractionControl_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return avisio_ivi.AvisioIviData.internal_static_avisio_ivi_SafetyStatus_descriptor;
      }

      @java.lang.Override
      public avisio_ivi.AvisioIviData.SafetyStatus getDefaultInstanceForType() {
        return avisio_ivi.AvisioIviData.SafetyStatus.getDefaultInstance();
      }

      @java.lang.Override
      public avisio_ivi.AvisioIviData.SafetyStatus build() {
        avisio_ivi.AvisioIviData.SafetyStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public avisio_ivi.AvisioIviData.SafetyStatus buildPartial() {
        avisio_ivi.AvisioIviData.SafetyStatus result = new avisio_ivi.AvisioIviData.SafetyStatus(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(avisio_ivi.AvisioIviData.SafetyStatus result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timestampMs_ = timestampMs_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.seatbeltFastened_ = seatbeltFastened_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.airbagOk_ = airbagOk_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.absActive_ = absActive_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.tractionControl_ = tractionControl_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof avisio_ivi.AvisioIviData.SafetyStatus) {
          return mergeFrom((avisio_ivi.AvisioIviData.SafetyStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(avisio_ivi.AvisioIviData.SafetyStatus other) {
        if (other == avisio_ivi.AvisioIviData.SafetyStatus.getDefaultInstance()) return this;
        if (other.getTimestampMs() != 0) {
          setTimestampMs(other.getTimestampMs());
        }
        if (other.getSeatbeltFastened() != false) {
          setSeatbeltFastened(other.getSeatbeltFastened());
        }
        if (other.getAirbagOk() != false) {
          setAirbagOk(other.getAirbagOk());
        }
        if (other.getAbsActive() != false) {
          setAbsActive(other.getAbsActive());
        }
        if (other.getTractionControl() != false) {
          setTractionControl(other.getTractionControl());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                timestampMs_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                seatbeltFastened_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                airbagOk_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                absActive_ = input.readBool();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                tractionControl_ = input.readBool();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int timestampMs_ ;
      /**
       * <code>uint32 timestamp_ms = 1;</code>
       * @return The timestampMs.
       */
      @java.lang.Override
      public int getTimestampMs() {
        return timestampMs_;
      }
      /**
       * <code>uint32 timestamp_ms = 1;</code>
       * @param value The timestampMs to set.
       * @return This builder for chaining.
       */
      public Builder setTimestampMs(int value) {

        timestampMs_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 timestamp_ms = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestampMs() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestampMs_ = 0;
        onChanged();
        return this;
      }

      private boolean seatbeltFastened_ ;
      /**
       * <code>bool seatbelt_fastened = 2;</code>
       * @return The seatbeltFastened.
       */
      @java.lang.Override
      public boolean getSeatbeltFastened() {
        return seatbeltFastened_;
      }
      /**
       * <code>bool seatbelt_fastened = 2;</code>
       * @param value The seatbeltFastened to set.
       * @return This builder for chaining.
       */
      public Builder setSeatbeltFastened(boolean value) {

        seatbeltFastened_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bool seatbelt_fastened = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeatbeltFastened() {
        bitField0_ = (bitField0_ & ~0x00000002);
        seatbeltFastened_ = false;
        onChanged();
        return this;
      }

      private boolean airbagOk_ ;
      /**
       * <code>bool airbag_ok = 3;</code>
       * @return The airbagOk.
       */
      @java.lang.Override
      public boolean getAirbagOk() {
        return airbagOk_;
      }
      /**
       * <code>bool airbag_ok = 3;</code>
       * @param value The airbagOk to set.
       * @return This builder for chaining.
       */
      public Builder setAirbagOk(boolean value) {

        airbagOk_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool airbag_ok = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAirbagOk() {
        bitField0_ = (bitField0_ & ~0x00000004);
        airbagOk_ = false;
        onChanged();
        return this;
      }

      private boolean absActive_ ;
      /**
       * <code>bool abs_active = 4;</code>
       * @return The absActive.
       */
      @java.lang.Override
      public boolean getAbsActive() {
        return absActive_;
      }
      /**
       * <code>bool abs_active = 4;</code>
       * @param value The absActive to set.
       * @return This builder for chaining.
       */
      public Builder setAbsActive(boolean value) {

        absActive_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>bool abs_active = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAbsActive() {
        bitField0_ = (bitField0_ & ~0x00000008);
        absActive_ = false;
        onChanged();
        return this;
      }

      private boolean tractionControl_ ;
      /**
       * <code>bool traction_control = 5;</code>
       * @return The tractionControl.
       */
      @java.lang.Override
      public boolean getTractionControl() {
        return tractionControl_;
      }
      /**
       * <code>bool traction_control = 5;</code>
       * @param value The tractionControl to set.
       * @return This builder for chaining.
       */
      public Builder setTractionControl(boolean value) {

        tractionControl_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>bool traction_control = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTractionControl() {
        bitField0_ = (bitField0_ & ~0x00000010);
        tractionControl_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:avisio_ivi.SafetyStatus)
    }

    // @@protoc_insertion_point(class_scope:avisio_ivi.SafetyStatus)
    private static final avisio_ivi.AvisioIviData.SafetyStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new avisio_ivi.AvisioIviData.SafetyStatus();
    }

    public static avisio_ivi.AvisioIviData.SafetyStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SafetyStatus>
        PARSER = new com.google.protobuf.AbstractParser<SafetyStatus>() {
      @java.lang.Override
      public SafetyStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SafetyStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SafetyStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public avisio_ivi.AvisioIviData.SafetyStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_avisio_ivi_PrimaryVehicleState_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_avisio_ivi_PrimaryVehicleState_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_avisio_ivi_SignalLightingStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_avisio_ivi_SignalLightingStatus_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_avisio_ivi_SafetyStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_avisio_ivi_SafetyStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025avisio_ivi_data.proto\022\navisio_ivi\"\316\001\n\023" +
      "PrimaryVehicleState\022\024\n\014timestamp_ms\030\001 \001(" +
      "\r\022\021\n\tspeed_kmh\030\002 \001(\002\0221\n\022current_drive_mo" +
      "de\030\003 \001(\0162\025.avisio_ivi.DriveMode\022\027\n\017batte" +
      "ry_percent\030\004 \001(\r\022\024\n\014motor_temp_c\030\005 \001(\005\022\023" +
      "\n\013odometer_km\030\006 \001(\r\022\027\n\017trip_distance_m\030\007" +
      " \001(\r\"[\n\024SignalLightingStatus\022\024\n\014timestam" +
      "p_ms\030\001 \001(\r\022\024\n\014turn_signals\030\002 \001(\r\022\027\n\017exte" +
      "rior_lights\030\003 \001(\r\"\200\001\n\014SafetyStatus\022\024\n\014ti" +
      "mestamp_ms\030\001 \001(\r\022\031\n\021seatbelt_fastened\030\002 " +
      "\001(\010\022\021\n\tairbag_ok\030\003 \001(\010\022\022\n\nabs_active\030\004 \001" +
      "(\010\022\030\n\020traction_control\030\005 \001(\010*|\n\tDriveMod" +
      "e\022\023\n\017DRIVE_MODE_PARK\020\000\022\026\n\022DRIVE_MODE_REV" +
      "ERSE\020\001\022\026\n\022DRIVE_MODE_NEUTRAL\020\002\022\024\n\020DRIVE_" +
      "MODE_DRIVE\020\003\022\024\n\020DRIVE_MODE_BRAKE\020\004b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_avisio_ivi_PrimaryVehicleState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_avisio_ivi_PrimaryVehicleState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_avisio_ivi_PrimaryVehicleState_descriptor,
        new java.lang.String[] { "TimestampMs", "SpeedKmh", "CurrentDriveMode", "BatteryPercent", "MotorTempC", "OdometerKm", "TripDistanceM", });
    internal_static_avisio_ivi_SignalLightingStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_avisio_ivi_SignalLightingStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_avisio_ivi_SignalLightingStatus_descriptor,
        new java.lang.String[] { "TimestampMs", "TurnSignals", "ExteriorLights", });
    internal_static_avisio_ivi_SafetyStatus_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_avisio_ivi_SafetyStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_avisio_ivi_SafetyStatus_descriptor,
        new java.lang.String[] { "TimestampMs", "SeatbeltFastened", "AirbagOk", "AbsActive", "TractionControl", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
