// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: avisio_ivi.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_avisio_5fivi_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_avisio_5fivi_2eproto

#include <cstdint>
#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_avisio_5fivi_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_avisio_5fivi_2eproto {
  static const ::uint32_t offsets[];
};
namespace avisio_ivi {
class PrimaryVehicleState;
struct PrimaryVehicleStateDefaultTypeInternal;
extern PrimaryVehicleStateDefaultTypeInternal _PrimaryVehicleState_default_instance_;
class SafetyStatus;
struct SafetyStatusDefaultTypeInternal;
extern SafetyStatusDefaultTypeInternal _SafetyStatus_default_instance_;
class SignalLightingStatus;
struct SignalLightingStatusDefaultTypeInternal;
extern SignalLightingStatusDefaultTypeInternal _SignalLightingStatus_default_instance_;
}  // namespace avisio_ivi
PROTOBUF_NAMESPACE_OPEN
template<> ::avisio_ivi::PrimaryVehicleState* Arena::CreateMaybeMessage<::avisio_ivi::PrimaryVehicleState>(Arena*);
template<> ::avisio_ivi::SafetyStatus* Arena::CreateMaybeMessage<::avisio_ivi::SafetyStatus>(Arena*);
template<> ::avisio_ivi::SignalLightingStatus* Arena::CreateMaybeMessage<::avisio_ivi::SignalLightingStatus>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace avisio_ivi {

enum Gear : int {
  GEAR_NEUTRAL = 0,
  GEAR_FIRST = 1,
  GEAR_SECOND = 2,
  GEAR_THIRD = 3,
  GEAR_FOURTH = 4,
  GEAR_FIFTH = 5,
  GEAR_SIXTH = 6,
  GEAR_REVERSE = 7,
  Gear_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::int32_t>::min(),
  Gear_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::int32_t>::max()
};
bool Gear_IsValid(int value);
constexpr Gear Gear_MIN = GEAR_NEUTRAL;
constexpr Gear Gear_MAX = GEAR_REVERSE;
constexpr int Gear_ARRAYSIZE = Gear_MAX + 1;

const std::string& Gear_Name(Gear value);
template<typename T>
inline const std::string& Gear_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Gear>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Gear_Name.");
  return Gear_Name(static_cast<Gear>(enum_t_value));
}
bool Gear_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Gear* value);
enum GearMode : int {
  GEAR_MODE_PARK = 0,
  GEAR_MODE_REVERSE = 1,
  GEAR_MODE_NEUTRAL = 2,
  GEAR_MODE_DRIVE = 3,
  GEAR_MODE_SPORT = 4,
  GEAR_MODE_MANUAL = 5,
  GearMode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::int32_t>::min(),
  GearMode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::int32_t>::max()
};
bool GearMode_IsValid(int value);
constexpr GearMode GearMode_MIN = GEAR_MODE_PARK;
constexpr GearMode GearMode_MAX = GEAR_MODE_MANUAL;
constexpr int GearMode_ARRAYSIZE = GearMode_MAX + 1;

const std::string& GearMode_Name(GearMode value);
template<typename T>
inline const std::string& GearMode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, GearMode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function GearMode_Name.");
  return GearMode_Name(static_cast<GearMode>(enum_t_value));
}
bool GearMode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, GearMode* value);
// ===================================================================

class PrimaryVehicleState final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:avisio_ivi.PrimaryVehicleState) */ {
 public:
  inline PrimaryVehicleState() : PrimaryVehicleState(nullptr) {}
  ~PrimaryVehicleState() override;
  explicit PROTOBUF_CONSTEXPR PrimaryVehicleState(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PrimaryVehicleState(const PrimaryVehicleState& from);
  PrimaryVehicleState(PrimaryVehicleState&& from) noexcept
    : PrimaryVehicleState() {
    *this = ::std::move(from);
  }

  inline PrimaryVehicleState& operator=(const PrimaryVehicleState& from) {
    if (this == &from) return *this;
    CopyFrom(from);
    return *this;
  }
  inline PrimaryVehicleState& operator=(PrimaryVehicleState&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const PrimaryVehicleState& default_instance() {
    return *internal_default_instance();
  }
  static inline const PrimaryVehicleState* internal_default_instance() {
    return reinterpret_cast<const PrimaryVehicleState*>(
               &_PrimaryVehicleState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PrimaryVehicleState& a, PrimaryVehicleState& b) {
    a.Swap(&b);
  }
  inline void Swap(PrimaryVehicleState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PrimaryVehicleState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PrimaryVehicleState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PrimaryVehicleState>(arena);
  }
  PrimaryVehicleState* New() const {
    return New(nullptr);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const PrimaryVehicleState& from);
  void MergeFrom(const PrimaryVehicleState& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PrimaryVehicleState* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "avisio_ivi.PrimaryVehicleState";
  }
  protected:
  explicit PrimaryVehicleState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimestampMsFieldNumber = 1,
    kSpeedKmhFieldNumber = 2,
    kEngineRpmFieldNumber = 3,
    kCurrentGearFieldNumber = 4,
    kGearModeFieldNumber = 5,
    kFuelLevelMillipercentFieldNumber = 6,
    kEngineTempCFieldNumber = 7,
    kStatusFlagsFieldNumber = 8,
    kOdometerKmFieldNumber = 9,
    kTripDistanceMFieldNumber = 10,
  };
  // uint32 timestamp_ms = 1;
  void clear_timestamp_ms();
  ::uint32_t timestamp_ms() const;
  void set_timestamp_ms(::uint32_t value);
  private:
  ::uint32_t _internal_timestamp_ms() const;
  void _internal_set_timestamp_ms(::uint32_t value);
  public:

  // float speed_kmh = 2;
  void clear_speed_kmh();
  float speed_kmh() const;
  void set_speed_kmh(float value);
  private:
  float _internal_speed_kmh() const;
  void _internal_set_speed_kmh(float value);
  public:

  // double engine_rpm = 3;
  void clear_engine_rpm();
  double engine_rpm() const;
  void set_engine_rpm(double value);
  private:
  double _internal_engine_rpm() const;
  void _internal_set_engine_rpm(double value);
  public:

  // .avisio_ivi.Gear current_gear = 4;
  void clear_current_gear();
  ::avisio_ivi::Gear current_gear() const;
  void set_current_gear(::avisio_ivi::Gear value);
  private:
  ::avisio_ivi::Gear _internal_current_gear() const;
  void _internal_set_current_gear(::avisio_ivi::Gear value);
  public:

  // .avisio_ivi.GearMode gear_mode = 5;
  void clear_gear_mode();
  ::avisio_ivi::GearMode gear_mode() const;
  void set_gear_mode(::avisio_ivi::GearMode value);
  private:
  ::avisio_ivi::GearMode _internal_gear_mode() const;
  void _internal_set_gear_mode(::avisio_ivi::GearMode value);
  public:

  // uint32 fuel_level_millipercent = 6;
  void clear_fuel_level_millipercent();
  ::uint32_t fuel_level_millipercent() const;
  void set_fuel_level_millipercent(::uint32_t value);
  private:
  ::uint32_t _internal_fuel_level_millipercent() const;
  void _internal_set_fuel_level_millipercent(::uint32_t value);
  public:

  // int32 engine_temp_c = 7;
  void clear_engine_temp_c();
  ::int32_t engine_temp_c() const;
  void set_engine_temp_c(::int32_t value);
  private:
  ::int32_t _internal_engine_temp_c() const;
  void _internal_set_engine_temp_c(::int32_t value);
  public:

  // uint32 status_flags = 8;
  void clear_status_flags();
  ::uint32_t status_flags() const;
  void set_status_flags(::uint32_t value);
  private:
  ::uint32_t _internal_status_flags() const;
  void _internal_set_status_flags(::uint32_t value);
  public:

  // uint32 odometer_km = 9;
  void clear_odometer_km();
  ::uint32_t odometer_km() const;
  void set_odometer_km(::uint32_t value);
  private:
  ::uint32_t _internal_odometer_km() const;
  void _internal_set_odometer_km(::uint32_t value);
  public:

  // uint32 trip_distance_m = 10;
  void clear_trip_distance_m();
  ::uint32_t trip_distance_m() const;
  void set_trip_distance_m(::uint32_t value);
  private:
  ::uint32_t _internal_trip_distance_m() const;
  void _internal_set_trip_distance_m(::uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:avisio_ivi.PrimaryVehicleState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::uint32_t timestamp_ms_;
    float speed_kmh_;
    double engine_rpm_;
    int current_gear_;
    int gear_mode_;
    ::uint32_t fuel_level_millipercent_;
    ::int32_t engine_temp_c_;
    ::uint32_t status_flags_;
    ::uint32_t odometer_km_;
    ::uint32_t trip_distance_m_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_avisio_5fivi_2eproto;
};
// -------------------------------------------------------------------

class SignalLightingStatus final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:avisio_ivi.SignalLightingStatus) */ {
 public:
  inline SignalLightingStatus() : SignalLightingStatus(nullptr) {}
  ~SignalLightingStatus() override;
  explicit PROTOBUF_CONSTEXPR SignalLightingStatus(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SignalLightingStatus(const SignalLightingStatus& from);
  SignalLightingStatus(SignalLightingStatus&& from) noexcept
    : SignalLightingStatus() {
    *this = ::std::move(from);
  }

  inline SignalLightingStatus& operator=(const SignalLightingStatus& from) {
    if (this == &from) return *this;
    CopyFrom(from);
    return *this;
  }
  inline SignalLightingStatus& operator=(SignalLightingStatus&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const SignalLightingStatus& default_instance() {
    return *internal_default_instance();
  }
  static inline const SignalLightingStatus* internal_default_instance() {
    return reinterpret_cast<const SignalLightingStatus*>(
               &_SignalLightingStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SignalLightingStatus& a, SignalLightingStatus& b) {
    a.Swap(&b);
  }
  inline void Swap(SignalLightingStatus* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SignalLightingStatus* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SignalLightingStatus* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SignalLightingStatus>(arena);
  }
  SignalLightingStatus* New() const {
    return New(nullptr);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const SignalLightingStatus& from);
  void MergeFrom(const SignalLightingStatus& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SignalLightingStatus* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "avisio_ivi.SignalLightingStatus";
  }
  protected:
  explicit SignalLightingStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimestampMsFieldNumber = 1,
    kTurnSignalsFieldNumber = 2,
    kExteriorLightsFieldNumber = 3,
  };
  // uint32 timestamp_ms = 1;
  void clear_timestamp_ms();
  ::uint32_t timestamp_ms() const;
  void set_timestamp_ms(::uint32_t value);
  private:
  ::uint32_t _internal_timestamp_ms() const;
  void _internal_set_timestamp_ms(::uint32_t value);
  public:

  // uint32 turn_signals = 2;
  void clear_turn_signals();
  ::uint32_t turn_signals() const;
  void set_turn_signals(::uint32_t value);
  private:
  ::uint32_t _internal_turn_signals() const;
  void _internal_set_turn_signals(::uint32_t value);
  public:

  // uint32 exterior_lights = 3;
  void clear_exterior_lights();
  ::uint32_t exterior_lights() const;
  void set_exterior_lights(::uint32_t value);
  private:
  ::uint32_t _internal_exterior_lights() const;
  void _internal_set_exterior_lights(::uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:avisio_ivi.SignalLightingStatus)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::uint32_t timestamp_ms_;
    ::uint32_t turn_signals_;
    ::uint32_t exterior_lights_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_avisio_5fivi_2eproto;
};
// -------------------------------------------------------------------

class SafetyStatus final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:avisio_ivi.SafetyStatus) */ {
 public:
  inline SafetyStatus() : SafetyStatus(nullptr) {}
  ~SafetyStatus() override;
  explicit PROTOBUF_CONSTEXPR SafetyStatus(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SafetyStatus(const SafetyStatus& from);
  SafetyStatus(SafetyStatus&& from) noexcept
    : SafetyStatus() {
    *this = ::std::move(from);
  }

  inline SafetyStatus& operator=(const SafetyStatus& from) {
    if (this == &from) return *this;
    CopyFrom(from);
    return *this;
  }
  inline SafetyStatus& operator=(SafetyStatus&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const SafetyStatus& default_instance() {
    return *internal_default_instance();
  }
  static inline const SafetyStatus* internal_default_instance() {
    return reinterpret_cast<const SafetyStatus*>(
               &_SafetyStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(SafetyStatus& a, SafetyStatus& b) {
    a.Swap(&b);
  }
  inline void Swap(SafetyStatus* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SafetyStatus* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SafetyStatus* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SafetyStatus>(arena);
  }
  SafetyStatus* New() const {
    return New(nullptr);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const SafetyStatus& from);
  void MergeFrom(const SafetyStatus& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SafetyStatus* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "avisio_ivi.SafetyStatus";
  }
  protected:
  explicit SafetyStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimestampMsFieldNumber = 1,
    kSeatbeltFastenedFieldNumber = 2,
    kAirbagOkFieldNumber = 3,
    kTractionControlFieldNumber = 5,
  };
  // uint32 timestamp_ms = 1;
  void clear_timestamp_ms();
  ::uint32_t timestamp_ms() const;
  void set_timestamp_ms(::uint32_t value);
  private:
  ::uint32_t _internal_timestamp_ms() const;
  void _internal_set_timestamp_ms(::uint32_t value);
  public:

  // bool seatbelt_fastened = 2;
  void clear_seatbelt_fastened();
  bool seatbelt_fastened() const;
  void set_seatbelt_fastened(bool value);
  private:
  bool _internal_seatbelt_fastened() const;
  void _internal_set_seatbelt_fastened(bool value);
  public:

  // bool airbag_ok = 3;
  void clear_airbag_ok();
  bool airbag_ok() const;
  void set_airbag_ok(bool value);
  private:
  bool _internal_airbag_ok() const;
  void _internal_set_airbag_ok(bool value);
  public:

  // bool traction_control = 5;
  void clear_traction_control();
  bool traction_control() const;
  void set_traction_control(bool value);
  private:
  bool _internal_traction_control() const;
  void _internal_set_traction_control(bool value);
  public:

  // @@protoc_insertion_point(class_scope:avisio_ivi.SafetyStatus)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::uint32_t timestamp_ms_;
    bool seatbelt_fastened_;
    bool airbag_ok_;
    bool traction_control_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_avisio_5fivi_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PrimaryVehicleState

// uint32 timestamp_ms = 1;
inline void PrimaryVehicleState::clear_timestamp_ms() {
  _impl_.timestamp_ms_ = 0u;
}
inline ::uint32_t PrimaryVehicleState::_internal_timestamp_ms() const {
  return _impl_.timestamp_ms_;
}
inline ::uint32_t PrimaryVehicleState::timestamp_ms() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.PrimaryVehicleState.timestamp_ms)
  return _internal_timestamp_ms();
}
inline void PrimaryVehicleState::_internal_set_timestamp_ms(::uint32_t value) {
  
  _impl_.timestamp_ms_ = value;
}
inline void PrimaryVehicleState::set_timestamp_ms(::uint32_t value) {
  _internal_set_timestamp_ms(value);
  // @@protoc_insertion_point(field_set:avisio_ivi.PrimaryVehicleState.timestamp_ms)
}

// float speed_kmh = 2;
inline void PrimaryVehicleState::clear_speed_kmh() {
  _impl_.speed_kmh_ = 0;
}
inline float PrimaryVehicleState::_internal_speed_kmh() const {
  return _impl_.speed_kmh_;
}
inline float PrimaryVehicleState::speed_kmh() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.PrimaryVehicleState.speed_kmh)
  return _internal_speed_kmh();
}
inline void PrimaryVehicleState::_internal_set_speed_kmh(float value) {
  
  _impl_.speed_kmh_ = value;
}
inline void PrimaryVehicleState::set_speed_kmh(float value) {
  _internal_set_speed_kmh(value);
  // @@protoc_insertion_point(field_set:avisio_ivi.PrimaryVehicleState.speed_kmh)
}

// double engine_rpm = 3;
inline void PrimaryVehicleState::clear_engine_rpm() {
  _impl_.engine_rpm_ = 0;
}
inline double PrimaryVehicleState::_internal_engine_rpm() const {
  return _impl_.engine_rpm_;
}
inline double PrimaryVehicleState::engine_rpm() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.PrimaryVehicleState.engine_rpm)
  return _internal_engine_rpm();
}
inline void PrimaryVehicleState::_internal_set_engine_rpm(double value) {
  
  _impl_.engine_rpm_ = value;
}
inline void PrimaryVehicleState::set_engine_rpm(double value) {
  _internal_set_engine_rpm(value);
  // @@protoc_insertion_point(field_set:avisio_ivi.PrimaryVehicleState.engine_rpm)
}

// .avisio_ivi.Gear current_gear = 4;
inline void PrimaryVehicleState::clear_current_gear() {
  _impl_.current_gear_ = 0;
}
inline ::avisio_ivi::Gear PrimaryVehicleState::_internal_current_gear() const {
  return static_cast< ::avisio_ivi::Gear >(_impl_.current_gear_);
}
inline ::avisio_ivi::Gear PrimaryVehicleState::current_gear() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.PrimaryVehicleState.current_gear)
  return _internal_current_gear();
}
inline void PrimaryVehicleState::_internal_set_current_gear(::avisio_ivi::Gear value) {
  
  _impl_.current_gear_ = value;
}
inline void PrimaryVehicleState::set_current_gear(::avisio_ivi::Gear value) {
  _internal_set_current_gear(value);
  // @@protoc_insertion_point(field_set:avisio_ivi.PrimaryVehicleState.current_gear)
}

// .avisio_ivi.GearMode gear_mode = 5;
inline void PrimaryVehicleState::clear_gear_mode() {
  _impl_.gear_mode_ = 0;
}
inline ::avisio_ivi::GearMode PrimaryVehicleState::_internal_gear_mode() const {
  return static_cast< ::avisio_ivi::GearMode >(_impl_.gear_mode_);
}
inline ::avisio_ivi::GearMode PrimaryVehicleState::gear_mode() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.PrimaryVehicleState.gear_mode)
  return _internal_gear_mode();
}
inline void PrimaryVehicleState::_internal_set_gear_mode(::avisio_ivi::GearMode value) {
  
  _impl_.gear_mode_ = value;
}
inline void PrimaryVehicleState::set_gear_mode(::avisio_ivi::GearMode value) {
  _internal_set_gear_mode(value);
  // @@protoc_insertion_point(field_set:avisio_ivi.PrimaryVehicleState.gear_mode)
}

// uint32 fuel_level_millipercent = 6;
inline void PrimaryVehicleState::clear_fuel_level_millipercent() {
  _impl_.fuel_level_millipercent_ = 0u;
}
inline ::uint32_t PrimaryVehicleState::_internal_fuel_level_millipercent() const {
  return _impl_.fuel_level_millipercent_;
}
inline ::uint32_t PrimaryVehicleState::fuel_level_millipercent() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.PrimaryVehicleState.fuel_level_millipercent)
  return _internal_fuel_level_millipercent();
}
inline void PrimaryVehicleState::_internal_set_fuel_level_millipercent(::uint32_t value) {
  
  _impl_.fuel_level_millipercent_ = value;
}
inline void PrimaryVehicleState::set_fuel_level_millipercent(::uint32_t value) {
  _internal_set_fuel_level_millipercent(value);
  // @@protoc_insertion_point(field_set:avisio_ivi.PrimaryVehicleState.fuel_level_millipercent)
}

// int32 engine_temp_c = 7;
inline void PrimaryVehicleState::clear_engine_temp_c() {
  _impl_.engine_temp_c_ = 0;
}
inline ::int32_t PrimaryVehicleState::_internal_engine_temp_c() const {
  return _impl_.engine_temp_c_;
}
inline ::int32_t PrimaryVehicleState::engine_temp_c() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.PrimaryVehicleState.engine_temp_c)
  return _internal_engine_temp_c();
}
inline void PrimaryVehicleState::_internal_set_engine_temp_c(::int32_t value) {
  
  _impl_.engine_temp_c_ = value;
}
inline void PrimaryVehicleState::set_engine_temp_c(::int32_t value) {
  _internal_set_engine_temp_c(value);
  // @@protoc_insertion_point(field_set:avisio_ivi.PrimaryVehicleState.engine_temp_c)
}

// uint32 status_flags = 8;
inline void PrimaryVehicleState::clear_status_flags() {
  _impl_.status_flags_ = 0u;
}
inline ::uint32_t PrimaryVehicleState::_internal_status_flags() const {
  return _impl_.status_flags_;
}
inline ::uint32_t PrimaryVehicleState::status_flags() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.PrimaryVehicleState.status_flags)
  return _internal_status_flags();
}
inline void PrimaryVehicleState::_internal_set_status_flags(::uint32_t value) {
  
  _impl_.status_flags_ = value;
}
inline void PrimaryVehicleState::set_status_flags(::uint32_t value) {
  _internal_set_status_flags(value);
  // @@protoc_insertion_point(field_set:avisio_ivi.PrimaryVehicleState.status_flags)
}

// uint32 odometer_km = 9;
inline void PrimaryVehicleState::clear_odometer_km() {
  _impl_.odometer_km_ = 0u;
}
inline ::uint32_t PrimaryVehicleState::_internal_odometer_km() const {
  return _impl_.odometer_km_;
}
inline ::uint32_t PrimaryVehicleState::odometer_km() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.PrimaryVehicleState.odometer_km)
  return _internal_odometer_km();
}
inline void PrimaryVehicleState::_internal_set_odometer_km(::uint32_t value) {
  
  _impl_.odometer_km_ = value;
}
inline void PrimaryVehicleState::set_odometer_km(::uint32_t value) {
  _internal_set_odometer_km(value);
  // @@protoc_insertion_point(field_set:avisio_ivi.PrimaryVehicleState.odometer_km)
}

// uint32 trip_distance_m = 10;
inline void PrimaryVehicleState::clear_trip_distance_m() {
  _impl_.trip_distance_m_ = 0u;
}
inline ::uint32_t PrimaryVehicleState::_internal_trip_distance_m() const {
  return _impl_.trip_distance_m_;
}
inline ::uint32_t PrimaryVehicleState::trip_distance_m() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.PrimaryVehicleState.trip_distance_m)
  return _internal_trip_distance_m();
}
inline void PrimaryVehicleState::_internal_set_trip_distance_m(::uint32_t value) {
  
  _impl_.trip_distance_m_ = value;
}
inline void PrimaryVehicleState::set_trip_distance_m(::uint32_t value) {
  _internal_set_trip_distance_m(value);
  // @@protoc_insertion_point(field_set:avisio_ivi.PrimaryVehicleState.trip_distance_m)
}

// -------------------------------------------------------------------

// SignalLightingStatus

// uint32 timestamp_ms = 1;
inline void SignalLightingStatus::clear_timestamp_ms() {
  _impl_.timestamp_ms_ = 0u;
}
inline ::uint32_t SignalLightingStatus::_internal_timestamp_ms() const {
  return _impl_.timestamp_ms_;
}
inline ::uint32_t SignalLightingStatus::timestamp_ms() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.SignalLightingStatus.timestamp_ms)
  return _internal_timestamp_ms();
}
inline void SignalLightingStatus::_internal_set_timestamp_ms(::uint32_t value) {
  
  _impl_.timestamp_ms_ = value;
}
inline void SignalLightingStatus::set_timestamp_ms(::uint32_t value) {
  _internal_set_timestamp_ms(value);
  // @@protoc_insertion_point(field_set:avisio_ivi.SignalLightingStatus.timestamp_ms)
}

// uint32 turn_signals = 2;
inline void SignalLightingStatus::clear_turn_signals() {
  _impl_.turn_signals_ = 0u;
}
inline ::uint32_t SignalLightingStatus::_internal_turn_signals() const {
  return _impl_.turn_signals_;
}
inline ::uint32_t SignalLightingStatus::turn_signals() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.SignalLightingStatus.turn_signals)
  return _internal_turn_signals();
}
inline void SignalLightingStatus::_internal_set_turn_signals(::uint32_t value) {
  
  _impl_.turn_signals_ = value;
}
inline void SignalLightingStatus::set_turn_signals(::uint32_t value) {
  _internal_set_turn_signals(value);
  // @@protoc_insertion_point(field_set:avisio_ivi.SignalLightingStatus.turn_signals)
}

// uint32 exterior_lights = 3;
inline void SignalLightingStatus::clear_exterior_lights() {
  _impl_.exterior_lights_ = 0u;
}
inline ::uint32_t SignalLightingStatus::_internal_exterior_lights() const {
  return _impl_.exterior_lights_;
}
inline ::uint32_t SignalLightingStatus::exterior_lights() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.SignalLightingStatus.exterior_lights)
  return _internal_exterior_lights();
}
inline void SignalLightingStatus::_internal_set_exterior_lights(::uint32_t value) {
  
  _impl_.exterior_lights_ = value;
}
inline void SignalLightingStatus::set_exterior_lights(::uint32_t value) {
  _internal_set_exterior_lights(value);
  // @@protoc_insertion_point(field_set:avisio_ivi.SignalLightingStatus.exterior_lights)
}

// -------------------------------------------------------------------

// SafetyStatus

// uint32 timestamp_ms = 1;
inline void SafetyStatus::clear_timestamp_ms() {
  _impl_.timestamp_ms_ = 0u;
}
inline ::uint32_t SafetyStatus::_internal_timestamp_ms() const {
  return _impl_.timestamp_ms_;
}
inline ::uint32_t SafetyStatus::timestamp_ms() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.SafetyStatus.timestamp_ms)
  return _internal_timestamp_ms();
}
inline void SafetyStatus::_internal_set_timestamp_ms(::uint32_t value) {
  
  _impl_.timestamp_ms_ = value;
}
inline void SafetyStatus::set_timestamp_ms(::uint32_t value) {
  _internal_set_timestamp_ms(value);
  // @@protoc_insertion_point(field_set:avisio_ivi.SafetyStatus.timestamp_ms)
}

// bool seatbelt_fastened = 2;
inline void SafetyStatus::clear_seatbelt_fastened() {
  _impl_.seatbelt_fastened_ = false;
}
inline bool SafetyStatus::_internal_seatbelt_fastened() const {
  return _impl_.seatbelt_fastened_;
}
inline bool SafetyStatus::seatbelt_fastened() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.SafetyStatus.seatbelt_fastened)
  return _internal_seatbelt_fastened();
}
inline void SafetyStatus::_internal_set_seatbelt_fastened(bool value) {
  
  _impl_.seatbelt_fastened_ = value;
}
inline void SafetyStatus::set_seatbelt_fastened(bool value) {
  _internal_set_seatbelt_fastened(value);
  // @@protoc_insertion_point(field_set:avisio_ivi.SafetyStatus.seatbelt_fastened)
}

// bool airbag_ok = 3;
inline void SafetyStatus::clear_airbag_ok() {
  _impl_.airbag_ok_ = false;
}
inline bool SafetyStatus::_internal_airbag_ok() const {
  return _impl_.airbag_ok_;
}
inline bool SafetyStatus::airbag_ok() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.SafetyStatus.airbag_ok)
  return _internal_airbag_ok();
}
inline void SafetyStatus::_internal_set_airbag_ok(bool value) {
  
  _impl_.airbag_ok_ = value;
}
inline void SafetyStatus::set_airbag_ok(bool value) {
  _internal_set_airbag_ok(value);
  // @@protoc_insertion_point(field_set:avisio_ivi.SafetyStatus.airbag_ok)
}

// bool traction_control = 5;
inline void SafetyStatus::clear_traction_control() {
  _impl_.traction_control_ = false;
}
inline bool SafetyStatus::_internal_traction_control() const {
  return _impl_.traction_control_;
}
inline bool SafetyStatus::traction_control() const {
  // @@protoc_insertion_point(field_get:avisio_ivi.SafetyStatus.traction_control)
  return _internal_traction_control();
}
inline void SafetyStatus::_internal_set_traction_control(bool value) {
  
  _impl_.traction_control_ = value;
}
inline void SafetyStatus::set_traction_control(bool value) {
  _internal_set_traction_control(value);
  // @@protoc_insertion_point(field_set:avisio_ivi.SafetyStatus.traction_control)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace avisio_ivi

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::avisio_ivi::Gear> : ::std::true_type {};
template <> struct is_proto_enum< ::avisio_ivi::GearMode> : ::std::true_type {};

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_avisio_5fivi_2eproto
